### ISSUE TITLE
Image link in running content (header and footer)

### ISSUE THREAD

**Issue by LilMouse** [asciidoctor/asciidoctor-pdf#1002]
I've been trying to use the image in my header as a clickable link.
It seems I can either use a text link or and image but not a clickable image.
The following creates a clickable link:
```
header:
  text: https://www.google.com[www.google.com]
  height: 1in
  recto:
    right:
      content: $header_text
  verso:
    right:
      content: $header_image
```

This creates a non clickable image:
```
header:
  #background_color: #eeeeee
  image: image:../Images/LogoSmall.png[width=150,link=www.google.com]
  height: 1in
  recto:
    right:
      content: $header_image
  verso:
    right:
      content: $header_image
```
It does work on the title_page_logo_image as follows
```
title_page:
  align: left
  line_height: 1.15
  title_font_size: $heading_h1_font_size
  subtitle_font_size: $heading_h2_font_size
  font_color: $heading_font_color
  logo_image: image:../Images/logobig.png[pdfwidth=40%,link=www.google.com]
```
This creates an image and a link separately but uses the wrong imagedir. It uses the from the main document instead of relative to the styles. That won't work because I try to reference this style from different places with their own image directory.

```
header:
  height: 1in
  recto:
    right:
      font_size: $base_font_size * 0.75
      content: |
       image:LogoSmall.png[width=100] +
       https://www.google.com[www.google.com]
```

So is there a way to either make my image clickable/a link in the header or make the last way of generating content use a directory relative to the styles dir?
