### ISSUE TITLE
Can't use alternative style for FontAwesome / prawn-icon

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#1005]
For example I can use the "default" lightbulb icon by setting:

```
  icon:
    tip:
      name: fa-lightbulb-o
      stroke_color: $brand_preferred_grass
      size: $base_font_size_ultralarge
```

This is shimmed to `far-lightbulb` so regular lightbulb.
https://github.com/jessedoyle/prawn-icon/blob/master/data/fonts/fa4/shims.yml#L248

If I try to replace this with `fas-lightbulb` it says:

````
Icon font not found for set: fas
  Use --trace for backtrace
```

How do I use the "solid" icons then? The PDF theming guide says the prefix selects the icon set but that doesn't seem to work.

I can use other icons that are not in the `shims.yml` just fine (e.g. fa-exclamation-circle, fa-info-circle).
