### ISSUE TITLE
Add configuration for PDF title page

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#1006]
I would love to see the ability to configure the title page a bit more.
Right now you are limited to title, subtitle and basically contributor and version info. 

In my case I would like to print the product and version number in a prominent place and add more style elements than a single logo and the background color/image. I've resorted to designing elaborate background images but all that they do could be achieved by giving us more control about how the title page works.

Can you expose more attributes/content of the actual document for use and give some options to generate a more intricate layout? My ideal thing would be something like this:

```
# Layout always needs to go on the bottom
title_page:
  content:
    logo:
      image: image:/some/image.png[pdfwidth=15%]
      align: left
      top: 5%
      left: 5%
    title:
      content: {title}
      font_size: 36
    product_name:
      content: {product_name}
      font_size: 24
    product_version:
      content: {product_version}
      font_size: 24
    authors:
      content: {authors}
      font_size: $brand_font_size
    revision:
      content: {product_number} {build_number} {build_date}
      font_size: $brand_font_size
    #render image on top of background color, specify X/Y pixel offset for display
    decoration_image:
      image: image:/path/to/image.(png|svg|jpg)[pdfwidth=X]
      align: right
      top: 30%
      left: 60%
  layout:
    $background_color
    #$background_image
    $logo
    $decoration_image
    #$title:$subtitle
    $title
    $subtitle
    $product_name
    $horizontal_rule
    $product_version
    $authors
    $revision
```
      
I hope you get the idea. I would love to be able to just expose all kinds of attributes and content from the input document to the processor so I can design it a bit more. Define some "PDF attribute" that uses some available attributes from the document and give me some way to get basic arrangement of these elements on the resulting page.

EDIT 2019-02-26:
With the HTML output we have SASS/CSS to do all kinds of things but the PDF output really is very limited at this point. At the same time this is one of the most asked for features for product documentation by enterprise customers and what they really care about (because you can "archive" it).
