### ISSUE TITLE
Footer page number is badly aligned when [.landscape] is used

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1036]
There is a new possibility to set page orientation #490 (which is really handy)

The issue is in footer to be rendered in unexpected way.

Having in the theme:
```
footer:
  font_size: $base_font_size_small
  height: $base_line_height_length * 3.0
  line_height: 1
  padding: [$base_line_height_length / 2, 1, 0, 1]
  vertical_align: top
  recto:
    right:
      content: '{page-number}'
  verso:
    right:
      content: '{page-number}'

```

and the file contents:

```
= Test
:experimental:
:icons: font
:autofit-option:
:source-highlighter: rouge
:rouge-style: github
:revdate: 2018-12-07
:imagesdir: images
:doctype: article
:toc:

== test 1
// 2019-04-22

Ut sed lacus id mauris mattis lobortis. Aliquam ut nisl eu neque viverra
pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam


[.landscape]
<<<
== hello
// 2019-04-16 12:26:58

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Maecenas feugiat fermentum pretium. Cras eu dolor imperdiet justo mattis
pulvinar. Cras nec lectus ligula. Proin elementum luctus elit, a tincidunt quam
facilisis non. Nunc quis mauris non turpis finibus luctus. Maecenas ante
sapien, sagittis quis accumsan in, feugiat quis sem. Praesent et auctor libero.

[.portrait]
<<<
== test

hello
```

It gets rendered like this (see the page number):

![image](https://user-images.githubusercontent.com/234774/56571688-26c6bf00-65c6-11e9-90a8-be19a71e4d29.png)
