### ISSUE TITLE
Table header

### ISSUE THREAD

**Issue by SandMann1** [asciidoctor/asciidoctor-pdf#104]
Hello. 
Is there any way to style the table header seperatly? I have can se that the rows kan be styled with different background colors on odd an even row numbers, but I can't find out how to style the tabel header.
With Regards
Ole

**Comment by mojavelinux** [comment]
It's not currently possible to change the background color of the table cell header. This would be something we'd need to add to the theme and pass to Prawn around the following line:

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L718

**Comment by mojavelinux** [comment]
You can now control the values using the following settings in the theme file:

```
table:
  background_color: <hex value>
  head_background_color: <hex value>
  head_font_color: <hex value>
  even_row_background_color: <hex value>
  odd_row_background_color: <hex value>
```

All values are optional. All values can also be the value "transparent", which allows the color underneath to shine through. For instance, here's how you set the background color of the table and the odd rows only.

```
table:
  background_color: f7f7f7
  odd_row_background_color: ffffff
```

So there are lots of options.
