### ISSUE TITLE
Settings of chapter of TOC and Preface

### ISSUE THREAD

**Issue by Alyaksej** [asciidoctor/asciidoctor-pdf#1040]
In my document, I set

```
running_content_start_at: toc
footer:
  ...
  recto:
    right:
      content: '{chapter-title}'
```

I got
![1](https://user-images.githubusercontent.com/36542108/56805055-77415500-6830-11e9-9967-e9205ac79bde.png)

How can I change 'Preface' to 'TOC' on footer of TOC or just remove this word from footer?
