### ISSUE TITLE
{chapter-title} reference contains formatting

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#1044]
The documentation shows `{chapter-title}` being used in the footer content as follows:

```
footer:
  …
  verso:
    left:
      content: '*{page-number}* | {chapter-title}'
```

This causes e.g.

**2** | Some title

to be rendered as footer. However, if you enable the section numbering via `:secnums:`, the rendering changes to include the label and chapter number:

**2** | Chapter 2. Some title

It looks like there's no way to refer to the sole title, is there?
