### ISSUE TITLE
Footer is isgnored 

### ISSUE THREAD

**Issue by marcdexet-cnrs** [asciidoctor/asciidoctor-pdf#1072]
Hi,

My context is 

* Asciidoctor PDF 1.5.0.alpha.17 using Asciidoctor 2.0.9
* Ruby 2.5.1p57 (2018-03-29 revision 63029) 

I have a pretty simple document and this theme configuration

```yaml
base:
  font_size: 10
  font_size_large: $base_font_size * 1.25
  font_size_small: $base_font_size * 0.85

footer:
  recto:
    right:
      content: '{page-number}'   
```

The theme is taken into account because font size change according to setting.

But the footer is still ignored.

Am I doing wrong or missing something ?

Thanks
