### ISSUE TITLE
Text is not printed on page header

### ISSUE THREAD

**Issue by tiagoma** [asciidoctor/asciidoctor-pdf#1087]
I have noticed this issue after upgrading from `asciidoctor-pdf-1.5.0.alpha.17` to `asciidoctor-pdf-1.5.0.alpha.18`:

* The page header text as specified in the YAML style file (for example in `header_recto_right_content`) is no longer being displayed in the page headers.
* Footer text is not affected and still being printed as expected.
* Images, both in header and footer, are displayed correctly.

See the output generated by each version:

[hello-1.5.0-alpha17.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3245697/hello-1.5.0-alpha17.pdf)
![1 5 0-alpha17](https://user-images.githubusercontent.com/38113517/58774309-2e02c480-8597-11e9-978e-3365c47a83c5.png)

[hello-1.5.0-alpha18.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3245698/hello-1.5.0-alpha18.pdf)
![1 5 0-alpha18](https://user-images.githubusercontent.com/38113517/58774316-33600f00-8597-11e9-879e-22016e908364.png)

Below the source:
```
= Hello
Hello
Hello

== Hello
Hello

<<<

== Hello
Hello
```

and the YAML style file:
```
page:
  layout: portrait
  margin: [0.75in, 1in, 0.75in, 1in]
  size: Letter
base:
  font_color: #333333
  font_family: Times-Roman
  font_size: 12
  line_height_length: 17
  line_height: $base_line_height_length / $base_font_size
vertical_spacing: $base_line_height_length
heading:
  font_color: #262626
  font_size: 17
  font_style: bold
  line_height: 1.2
  margin_bottom: $vertical_spacing
link:
  font_color: #002FA7
outline_list:
  indent: $base_font_size * 1.5
footer:
  height: $base_line_height_length * 2.5
  line_height: 1
  recto:
    center:
      content: image:octocat.jpg[pdfwidth=10mm]
    right:
      content: 'Hello {page-number}'
  verso:
    center:
      content: $footer_recto_center_content
    left:
      content: $footer_recto_right_content
header:
  height: $base_line_height_length * 2.5
  line_height: 1
  recto:
    center:
      content: image:octocat.jpg[pdfwidth=10mm]
    right:
      content: '{page-number} Hello'
  verso:
    center:
      content: $header_recto_center_content
    left:
      content: $header_recto_right_content
```
