### ISSUE TITLE
Header recto content seems broken

### ISSUE THREAD

**Issue by programming-wolf** [asciidoctor/asciidoctor-pdf#1106]
After upgrading to the latest release (alpha 18), I have a strange issue of having no text in my header. I define my header like this:

```
header:
  height: 2.5cm
  image_vertical_align: bottom
  vertical_align: bottom
  border_color: dddddd
  recto:
    center:
      content: "Here is my text"
    right:
      content: image:../logo-without-text.jpg[width=130]
  verso:
    left:
      content: $header_recto_left_content
    right:
      content: $header_recto_right_content
```

This worked fine with alpha 17, producing the logo on the right and a specific text on the left. 

Now there is no more text. The logo is still here, but the text is not rendered. If I remove the logo and replace it with text, there is nothing at all in the header. Could this be related to the changes of #1063 or, rather, #1068 ?
