### ISSUE TITLE
running-content-start-at not respected

### ISSUE THREAD

**Issue by andraz-kozelj** [asciidoctor/asciidoctor-pdf#1131]
I have a title page, toc and body. Header/footer are not shown on TOC page, even if 
```
running-content:
  start-at: toc
```
is defined.
Using 1.5.0.alpha.18

Find relevant parts of my theme:
```
better:
  color:
    vividblue: #026FD0
    darkblue: #035693
    font: #1D4056
    lightblue: #B7D2EE
    lighterblue: #DEEBFF
    lightgray: #f2f2f2
    lightgray2: #fafafa
    gray: #d8d8d8
    darkgray: #cccccc
    orange: #C05717

title:
  page: 
    background:
      image: image::cover-blue.png[]
    font:
      color: #ffffff
      size: 14
    align: right
    title:
      top: 60%
      font:
        color: #ffffff
        style: bold
        size: 20
    subtitle:
      font:
        color: #ffffff
        style: normal
        size: 20
    revision:
      font:
        size: 12
        delimiter: ' - '
page:
  layout: portrait
  margin: [1.3in, 0.75in, 1in, 0.75in]
  size: A4
base:
  font:
    color: $better_color_font
    family: OpenSans
    size: 10
  line:
    height: $base_line_height_length / $base_font_size
    length: 14
running-content:
  start-at: toc
toc:
  dot-leader:
    font-color: $better_color_darkgray
header:
  padding: [0.35in, 0, 0.5, -0.35in]
  height: 1in
  vertical-align: center
  font:
    size: $base_font_size * 0.9
    color: $better_color_darkblue
  recto:
    left:
      content: 'image:better_platform_header_logo.png[width="140"]'
    right:
      content: '{doctitle}'
  verso:
    left:
      content: 'image:better_platform_header_logo.png[width="140"]'
    right:
      content: '{doctitle}'
footer:
  height: 0.75in
  font:
    size: $base_font_size * 0.9
    color: $better_color_darkblue
  recto:
    right: 
      content: '{page-number}'
    left:
      content: '{doctitle}'
  verso:
    right: 
      content: '{page-number}'
    left: 
      content: '{doctitle}'
vertical:
  spacing: $base_line_height_length
heading:
  font:
    family: LibreFranklin
    color: $better_color_font
    size: 17
    style: bold
  line:
    height: 1.2
  margin:
    bottom: $vertical_spacing
link:
  font:
    color: $better_color_vividblue
```
