### ISSUE TITLE
Callout number (conum) not rendered in the source block

### ISSUE THREAD

**Issue by andraz-kozelj** [asciidoctor/asciidoctor-pdf#1162]
1.5.0.beta.1

Asciidoctor produces HTML just fine, PDF has legend printed, styled, but no conums in the block code. I switched off the source formatter (rouge) and result is the same.

My source
```
----
SELECT c
FROM EHR e <1>
CONTAINS COMPOSITION c <2>
----
<1> legend1
<2> legend2 
```

My theme:
```
base:
  font:
    family: OpenSans
    size: 10
  line:
    height: $base_line_height_length / $base_font_size
    length: 14
code:
  background:
    color: #333333
  border:
    radius: 5
    color: #333333
  font:
    size: 7
    family: Code
    color: #ffffff
conum:
  font:
    family: M+ 1mn
    color: #ffffff
    size: $base_font_size
  line:
    height: 4 / 3
font:
  catalog:
    OpenSans:
      normal: OpenSans-Regular.ttf
      italic: OpenSans-Italic.ttf
      bold: OpenSans-Bold.ttf
      bold_italic: OpenSans-BoldItalic.ttf
    Code:
      normal: RobotoMono-Regular.ttf
      italic: RobotoMono-Italic.ttf
      bold: RobotoMono-Bold.ttf
      bold_italic: RobotoMono-BoldItalic.ttf
    M+ 1mn:
      normal: mplus1mn-regular-ascii-conums.ttf
      bold: mplus1mn-bold-ascii.ttf
      italic: mplus1mn-italic-ascii.ttf
      bold_italic: mplus1mn-bold_italic-ascii.ttf
    Noto Serif:
      normal: notoserif-regular-subset.ttf
  fallbacks: Noto Serif 
```

![image](https://user-images.githubusercontent.com/2230309/61456845-5f78f900-a967-11e9-9c98-8b8b39ea728a.png)
