### ISSUE TITLE
Default table alignment from theme

### ISSUE THREAD

**Issue by dalemartin** [asciidoctor/asciidoctor-pdf#1164]
Currently we have
```
image:
  align: left | center | right
caption:
  align: left | center | right
```
Proposing a matching key for tables:
```
table:
  align: left | center | right
```
Should be able to override using the current `align="left | center | right"` property for individual placement.
