### ISSUE TITLE
Bad page rendering: margins are off the page

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1170]
asciidoctor-pdf version: current master

![image](https://user-images.githubusercontent.com/234774/61626678-93655e80-ac86-11e9-94e4-da91695b2901.png)

![image](https://user-images.githubusercontent.com/234774/61626657-86e10600-ac86-11e9-8c22-96a8c3775b18.png)

test theme and test doc is in archive
[testdoc.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/3416865/testdoc.zip)

result pdf with `mytest` theme
[testpage.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3416867/testpage.pdf)

With the default built in theme everything is OK though.

If I do minor changes to the test document -- margins are either ok or slighly wrong -- I couldn't figure out exactly what is the root cause of the issue.

**Comment by habamax** [comment]
I have just checked with 4642974c2b4557e679cbb08ec4092d4d36baea22 -- it has no such a problem:

![image](https://user-images.githubusercontent.com/234774/61627054-85fca400-ac87-11e9-8ef3-8d83330b3dd7.png)

**Comment by habamax** [comment]
And 1390e3535b6854110737b4ffaeefb67937140306 which was introduce by me :) causes the issue.

But the changes there was only about default table alignment...

**Comment by habamax** [comment]
So,
 
```
table:
  align: center
```

makes the test document crazy (as well as `aligh: right`)

**Comment by mojavelinux** [comment]
I tried the files you sent me and I don't get the result that you get. Are you sure  you are synced with master?

**Comment by mojavelinux** [comment]
> makes the test document crazy (as well as aligh: right)

That tells me something is wrong with your master branch, because that is extremely unlikely.

**Comment by habamax** [comment]
Yes, I have just double checked -- `git pull upstream master`

With the `mytheme` I got this exact result when `table_align: center`

**Comment by habamax** [comment]
So I change the table_align from center to left and document renders OK.

**Comment by mojavelinux** [comment]
I would clone the repo again and start with a clean workspace. Something
got misconfigured.

**Comment by habamax** [comment]
It looks like the issue somehow connected to the fonts...

```
font:
  catalog:
    Main:
      normal: NotoSerif-Regular.ttf
      bold: NotoSerif-Bold.ttf
      italic: NotoSerif-RegularItalic.ttf
      bold_italic: NotoSerif-BoldItalic.ttf
    Mono:
      normal: mplus-1mn-regular.ttf
      bold: mplus-1mn-bold.ttf
      italic: mplus-1mn-regular.ttf
      bold_italic: mplus-1mn-regular.ttf
    Heading:
      normal: OpenSans-Regular.ttf
      bold: OpenSans-Bold.ttf
      italic: OpenSans-Italic.ttf
      bold_italic: OpenSans-BoldItalic.ttf
    Literal:
      normal: mplus-1mn-regular.ttf
      bold: mplus-1mn-bold.ttf
      italic: mplus-1mn-regular.ttf
      bold_italic: mplus-1mn-regular.ttf
    Caption:
      normal: OpenSans-Regular.ttf
      bold: OpenSans-Bold.ttf
      italic: OpenSans-Italic.ttf
      bold_italic: OpenSans-BoldItalic.ttf

```

If I change noto serifs to open sans for Main section then rendering is OK.
