### ISSUE TITLE
Allow font-based icon keys and colors to be set by the theme

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#121]
Allow the font-based icons that are used when the document attribute `icons` is set to `font` to be customized using the theme. Currently, the icon data is hard-coded as a constant.

**Comment by mojavelinux** [comment]
One possibility is something like:

```
admonition:
  icons:
    caution:
      key: fa-fire
      color: ff0000
```

The prefix (in this case, `fa-`) determines the font set from which the icon will taken. We could split the key into `set` and `id`, but I think people will appreciate the shorthand.

**Comment by VickyatPWs** [comment]
so it is 'fa' (font set) and 'fire' (for unicode name?)
That's very good. 
Great, that one can define its color also.

Would it be here possible to maybe also set the font-size of the symbols? If they come from different font sets you may want to size them differently. 

Thanks

**Comment by mojavelinux** [comment]
Indeed!

**Comment by mojavelinux** [comment]
Since we are allowing the size of the icon to be set, we need to adjust the width of the label area accordingly. Right now it's hardcoded as `bounds.width / 12.0`.

**Comment by mojavelinux** [comment]
If necessary, we can handle that in a follow-up issue.

**Comment by mojavelinux** [comment]
We decided to go with the following syntax:

```yaml
admonition:
  icon:
    caution:
      name: fa-fire
      stroke_color: ff0000
      size: 24
```

Thanks to @jessedoyle for implementing this feature!
