### ISSUE TITLE
Replaces hyphens with underscores in theme keys for admonition icon type

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1217]
The theme keys for the admonition icon type are escaping the hyphen to underscore translation. As a result, it's not possible to use hyphens in key names for defining the properties of an admonition icon.

Failing scenario:

```yml
admonition:
  icon:
    important:
      stroke-color: ff0000
```

The workaround is to use an underscore in the key for stroke color instead:

```yml
admonition:
  icon:
    important:
      stroke_color: ff0000
```
