### ISSUE TITLE
Allow to define the text background and border on inline marks (with a custom role)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-pdf#1237]
Consider the following AsciiDoc document:

```adoc
[.hello]#bonjour#
```

In the theme file, I want to be able to define the background color:

```yml
role:
  hello:
    background-color: #f0f0f0
```

It should also be possible to configure the border:

* `border-radius`
* `border-offset`
* `border-width`
* `border-color`
