### ISSUE TITLE
The key font_catalog is not recognized as a font catalog in the theme file (yaml)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-pdf#1243]
I believe this is a regression in [v1.5.0.beta.3](https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.5.0.beta.3) (ie. I'm pretty sure it was working in v1.5.0.beta.2 or at least it was silently failing).

Now an exception is thrown:

> Calibri is not a known font. (Prawn::Errors::UnknownFont)

While debugging, I've noticed that `theme.font_catalog` was `nil` even though my theme file contains a font catalog:

```yml
font_catalog:
    Calibri:
        normal: calibri.ttf
        bold: calibrib.ttf
        italic: calibrii.ttf
```

As a result the fonts are not registered:

https://github.com/asciidoctor/asciidoctor-pdf/blob/f36960ad3d6c6018939914228b40734b71c898f2/lib/asciidoctor-pdf/converter.rb#L3319-L3320
