### ISSUE TITLE
Problems using custom font

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor-pdf#1270]
Hi!

I'm running into a lot of problems when trying to use a custom font with the latest version of asciidoctor-pdf (1.5.0 Beta 4).
I call it as follows:
```
RUBYOPT="-E utf-8" asciidoctor-pdf \
        -a pdf-theme=config/pdf-theme.yml \
        -a pdf-fontsdir="fonts-pdf;GEM_FONTS_DIR" \
        -r asciidoctor-diagram \
        index.adoc
```

I've read that version 1.5.0 Beta 4 removed the colon as valid separator, so I'm using a semi colon.

`config/pdf-theme.yml` looks like this:
```
# extends: default

font:
  catalog:
    DINWebPro:
      normal: DINWebPro.ttf
      bold: DINWebPro-Bold.ttf
      # italic: DINWebPro-Ita.ttf

base:
  font-family: DINWebPro

heading:
  font-family: DINWebPro
```
The fonts mentioned here are under `fonts-pdf/DINWebPro.ttf` and `fonts-pdf/DINWebPro-Bold.ttf`. I don't have the italic version yet, which is why I commented it out.

I'm calling asciidoctor-pdf from root, which means I have config and fonts just like described above.

This seems correct to me, according to the theming guide at [Custom Font](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#custom-fonts) and [Applying your Theme](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#applying-your-theme).

But, asciidoctor exits with: ` is not a known font.`

My asciidoc document is valid, a previous alpha version was able to convert it, it just ignored all the font specific options and used the asciidoc embedded ones.
The PDF without the custom font looks good, but it is the requirement of my company to use the company internal font.
I'm on Windows in case that makes a difference.

I'm at the end of my limited knowledge, either this is a bug of some sort or I am doing something wrong that I didn't find in the documentation (or it's not in the documentation). Any help would be greatly appreciated.
