### ISSUE TITLE
Text directly under header rendered wrong

### ISSUE THREAD

**Issue by PascalDutch** [asciidoctor/asciidoctor-pdf#1330]
When I type for example 
```
[discrete]
== Header

Author: {author} +
Version: {version}
```
Author and version are rendered in another fontsize (smaller than the header but bigger than the normal text) than expected, I think they might be seen as a sub header? Or am I doing something wrong?

**Comment by PascalDutch** [comment]
It seems to work when I remove the `[discrete]` thing. However, I don't want the header in the TOC

**Comment by PascalDutch** [comment]
I think I fixed the issue by putting the text in a text block with `--`

**Comment by mojavelinux** [comment]
It should not be necessary to put the content in a block and the text that follows a discrete heading should not be affected by that heading. Can you please provide a complete example? Are you using a custom theme?

**Comment by PascalDutch** [comment]
Thanks for the reply. Yes, I am using a custom theme:
``` 
extends: default
page:
  layout: portrait
  margin: [0.75in, 1in, 0.75in, 1in]
  size: Book
base:
  font-color: #333333
  font-family: Noto Serif
  # font-size: 12
  # line-height-length: 15
  # line-height: $base-line-height-length / $base-font-size
vertical-spacing: $base-line-height-length
header:
  font_color: 999999
  height: 0.5in
  recto:
    columns: "<40% =20% >40%"
    right:
      content: '_{organization}_'
    center:
      content: image:image.png[pdfwidth=0.50in]
  verso:
    columns: $header_recto_columns
    left:
      content: $header_recto_right_content
    center:
      content: $header_recto_center_content
heading:
  font-color: #262626
  font-size: 17
  font-style: bold
  line-height: 1.2
  margin-bottom: $vertical-spacing
link:
  font-color: #333333
  # font-style: bold
outline-list:
  indent: $base-font-size * 1.5
  text-align: left
footer:
  height: 0.45in
  recto:
    right:
      content: '{section-or-chapter-title} | {page-number}'
  verso:
    left:
      content: '{page-number} | {chapter-title}'
```
AsciiDoc code:
``` 
[discrete]
== Some title
[discrete]
=== Title1
[.text-left]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
[discrete]
=== Title2
[.text-left]
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

<<<
```
