### ISSUE TITLE
Removing page number from page

### ISSUE THREAD

**Issue by PascalDutch** [asciidoctor/asciidoctor-pdf#1331]
Is there a way to remove a page number from a page (or to start page numbering on a different page)? I need to define a cover page, titlepage and then the rest of the document. The title and cover page are nearly the same and netither are allowed to have page numbering

**Comment by PascalDutch** [comment]
In addition to the above statement, I also need to be able to exclude the page number from, for example, the summary. I searched the web but couldn't find an answer that suits my needs

**Comment by mojavelinux** [comment]
> I need to define a cover page, titlepage and then the rest of the document. The title and cover page are nearly the same and netither are allowed to have page numbering

That's exactly what the converter does by default (assuming the doctype is book or the title-page attribute is set). Are you observing different behavior? Can you provide a complete example?

It should look something like this:

```
= Document Title
:doctype: book
:front-cover-image: image:cover.jpg[]

first page of content
```

The page number will only appear on the first page of content.

Keep in mind you can control the page at which the running content starts using the [start_at key](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-running-content) in the theme.

> I also need to be able to exclude the page number from, for example, the summary

That's not possible with Asciidoctor PDF.

**Comment by PascalDutch** [comment]
I don't think I am experiencing different behaviour, I think it is just me doing something wrong (kind of new to AsciiDoctor). For clarity, my root doc settings file (omitted file includes for brevity):
```
= Title
:title: Title
:author: Pascal
:bibliography-database: db_citaten_stage.bib
:bibliography-style: apa
:bibtex-style: apa
:bibliography-tex-style: numeric
:bibtex-order: appearance
:title-logo-image: image:someImage.png[pdfwidth=4.25in,align=center]
Pascal <mail@addres.com>
v0.1, October 2019
:doctype: book
:front-cover-image: image:image1.png[]
// Settings:
:experimental:
:reproducible:
:icons: font
:listing-caption: Listing
:sectnums:
:toc: macro
:toclevels: 3
:toc-title: Inhoudsopgave
:chapter-label:
:stem: latexmath
:align-text: left
ifeval::["{asciidoctor-version}" < "1.5.7"]
:legacy-footnoteref:
endif::[]
ifdef::backend-pdf[]
:pdf-theme: onderzoekSjabloon-theme.yml
:pdf-themesdir: sjablonen
:source-highlighter: coderay
endif::[]
```

Is it possible to use a AsciiDoc file as the front cover? Or is an image the only option (I think so since it says front-cover-*image*). 

Also, defining
 ```
running-content:
  start-at: toc
``` 
in my theme does not seem to do anything, but I'm not quite sure what it is supposed to do. Does it determine where the page numbering starts (that is exactly what I'm looking for!)? My current YAML file:
```
extends: default
running-content:
  start-at: toc
page:
  layout: portrait
  margin: [0.75in, 1in, 0.75in, 1in]
  size: Book
base:
  font-color: #333333
  font-family: Noto Serif
vertical-spacing: $base-line-height-length
header:
  font_color: 999999
  height: 0.5in
  recto:
    columns: "<40% =20% >40%"
    right:
      content: '_{organization}_'
    center:
      content: image:image1.png[pdfwidth=0.50in]
  verso:
    columns: $header_recto_columns
    left:
      content: $header_recto_right_content
    center:
      content: $header_recto_center_content
heading:
  font-color: #262626
  font-size: 17
  font-style: bold
  line-height: 1.2
  margin-bottom: $vertical-spacing
link:
  font-color: #333333
  # font-style: bold
outline-list:
  indent: $base-font-size * 1.5
  text-align: left
footer:
  height: 0.45in
  recto:
    right:
      content: '{section-or-chapter-title} | {page-number}'
  verso:
    left:
      content: '{page-number} | {chapter-title}'
``` 

Thanks for the support!

**Comment by mojavelinux** [comment]
> Is it possible to use a AsciiDoc file as the front cover?

No, but you can use a page from a PDF file (which is perhaps created by Asciidoctor PDF).

**Comment by mojavelinux** [comment]
> in my theme does not seem to do anything, but I'm not quite sure what it is supposed to do.

It starts the running content on the first page of the toc (instead of the first page of the content / body).

**Comment by mojavelinux** [comment]
Your problem seems to be that you have not actually enabled the toc. The toc attribute is not set.

**Comment by PascalDutch** [comment]
I defined the toc attribute between the includes (which I left out for brevity).
Other half of the above AsciiDoc code:

```
include::voorblad.adoc[]

include::versiebeheer.adoc[]

include::samenvatting.adoc[]

toc::[]

include::woordenlijst.adoc[]

include::inleiding.adoc[]

include::hoofdstuk1.adoc[]

include::hoofdstuk2.adoc[]

== Bronnen
[.text-left]
bibliography::[]

**Comment by mojavelinux** [comment]
That's not the attribute. That's the toc macro. If you want to use it, you
still need this in your header:

:toc: macro

**Comment by PascalDutch** [comment]
```
= Title
:title: Title
:author: Pascal
:bibliography-database: db_citaten_stage.bib
:bibliography-style: apa
:bibtex-style: apa
:bibliography-tex-style: numeric
:bibtex-order: appearance
:title-logo-image: image:someImage.png[pdfwidth=4.25in,align=center]
Pascal <mail@addres.com>
v0.1, October 2019
:doctype: book
:front-cover-image: image:image1.png[]
// Settings:
:experimental:
:reproducible:
:icons: font
:listing-caption: Listing
:sectnums:
:toc: macro <---- toc attribute
:toclevels: 3
:toc-title: Inhoudsopgave
:chapter-label:
:stem: latexmath
:align-text: left
ifeval::["{asciidoctor-version}" < "1.5.7"]
:legacy-footnoteref:
endif::[]
ifdef::backend-pdf[]
:pdf-theme: onderzoekSjabloon-theme.yml
:pdf-themesdir: sjablonen
:source-highlighter: coderay
endif::[]
```
Thanks for the quick response, I am aware that I need that in the header and I in fact have (pointed out above). The toc is, in fact, generated correctly. No worries whatsoever on that side.

**Comment by mojavelinux** [comment]
the start-at: toc is only relevant when the toc is in the default location,
so it won't change anything in your case.

**Comment by mojavelinux** [comment]
I still say that it's already doing what you describe here:

> The title and cover page are nearly the same and neither are allowed to have page numbering

So what are you observing? Can you post a PDF?

**Comment by mojavelinux** [comment]
> Does (`running-content: start-page`) determine where the page numbering starts (that is exactly what I'm looking for!)

No, that determines the page on which the running content starts. If you want to change where page numbering starts, that's `page: numbering-start-at`. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-page. But since you're using manual placement for the toc, changing this setting won't likely do you any good.

Can you describe in more detail what you actually want to achieve? It's still not clear to me.

**Comment by PascalDutch** [comment]
I wan't the page numbering to start at the toc, since the summary, glossary, titlepage, preface, etc. are not supposed (at least in my situation) to have page numbering. 

I can't, however, get this working. Looking at the [report.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3737432/report.pdf), I hope my problem becomes clearer. As you can see, the page numbering begins after the title page, even when I use `page: numbering-start-at` in my themes file. 

The code I used to generate above pdf:
AsciiDoc:
```
 
= Title
:doctype: book
:version: 0.1
:bibliography-database: db_citaten_stage.bib
:bibliography-style: apa
:bibtex-style: apa
:bibliography-tex-style: numeric
:bibtex-order: appearance
:title-logo-image: image:Plaatjes/sample-banner.svg[pdfwidth=4.25in,align=center]
Pascal <mail@mail.com>
v0.1, October 2019
:front-cover-image: image:Plaatjes/sample-banner.svg[.png[]
// Settings:
:experimental:
:reproducible:
:icons: font
:sectnums:
:toc: macro
:toclevels: 3
:chapter-label:
:stem: latexmath
:align-text: left

ifeval::["{asciidoctor-version}" < "1.5.7"]
:legacy-footnoteref:
endif::[]
ifdef::backend-pdf[]
:pdf-theme: onderzoekSjabloon-theme.yml
:pdf-themesdir: sjablonen
:source-highlighter: coderay
endif::[]

include::titlePage.adoc[]

include::versionHistory.adoc[]

include::summary.adoc[]

toc::[]

include::wordlist.adoc[]

include::preface.adoc[]

include::chapter1.adoc[]

include::chapter2.adoc[]

== Bronnen
[.text-left]
bibliography::[]
```
YAML theme file:
```

extends: default
running-content:
  start-at: toc
page:
  layout: portrait
  margin: [0.75in, 1in, 0.75in, 1in]
  size: Book
  numbering-start-at: toc
base:
  font-color: #333333
  font-family: Noto Serif
vertical-spacing: $base-line-height-length
header:
  font_color: 999999
  height: 0.5in
  recto:
    columns: "<40% =20% >40%"
    right:
      content: '_{organization}_'
    center:
      content: image:plaatjes/sample-banner.svg[pdfwidth=0.50in]
  verso:
    columns: $header_recto_columns
    left:
      content: $header_recto_right_content
    center:
      content: $header_recto_center_content
heading:
  font-color: #262626
  font-size: 17
  font-style: bold
  line-height: 1.2
  margin-bottom: $vertical-spacing
link:
  font-color: #333333
  # font-style: bold
outline-list:
  indent: $base-font-size * 1.5
  text-align: left
footer:
  height: 0.45in
  recto:
    right:
      content: '{section-or-chapter-title} | {page-number}'
  verso:
    left:
      content: '{page-number} | {chapter-title}'
```

I'm sure I am doing something wrong here. I can't, however, figure out what.
