### ISSUE TITLE
Image aligment in `logo` overriden by `title-page` when value is invalid

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-pdf#1352]
**First**, I have a related question of "which are the valid alignments for images?". According to this https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#image-alignments, the valid values are left, center, right. Does that mean top or bottom are not allowed?

**Secondly**, when using an align value that is not _left, center or right_, (including empty value) the value is overriden by the one set in title_page. If the idea is to override when the attribute is present, I think that at least it should check the value is valid, and show a message if it is not.

The following configuration will display the image centered and the text to the left,
```yml
title_page:
  align: left
  logo:
    image: image:cover.png[]
```

These ones, puts everything to the left.
```yml
title_page:
  align: left
  logo:
    image: image:cover.png[align=]
```

```yml
title_page:
  align: left
  logo:
    image: image:cover.png[align=top]
```

I reproduced with the Ruby cli:
asciidoctor (2.0.10)
asciidoctor-pdf (1.5.0.beta.6)
