### ISSUE TITLE
Missing values and blank pages when adjusting `prose_margin_bottom` alongside `a` for table column type

### ISSUE THREAD

**Issue by myii** [asciidoctor/asciidoctor-pdf#1369]
#### Related issue

May be related to #926.

#### Asciidoctor file

```adoc
= Bug: Using `a` for table column type

.Content is not displayed *and* results in blank page(s)
[format="psv", cols="a"]
|===
|
* abc
|===
```

#### Theme

```yaml
---
extends: default
base:
  font_family: M+ 1mn
  ### For testing with `prose_margin_bottom: 0`
  # line_height: 1
prose:
  ### Can get this working with `base_line_height: 1` but with an extra blank page
  # margin_bottom: 0

  ### Content isn't displayed with the default value of `base_line_height`
  # margin_bottom: 1
  margin_bottom: 2

  ### Content is displayed but an extra blank page is still produced
  # margin_bottom: 3
  # margin_bottom: 4
  # margin_bottom: 5

  ### Lowest value that works without issues using the default `base_line_height`
  # margin_bottom: 6
```

* Another important factor is the `font_family` that it used; some are affected more adversely than others.

#### Command

```bash
$ asciidoctor-pdf -a pdf-theme=bug_using-type-a-for-table-column.yml bug_using-type-a-for-table-column.adoc
```

#### Result

![screenshot103](https://user-images.githubusercontent.com/10231489/68222133-6bee9380-ffe2-11e9-8a56-1dbbb371f83b.png)

#### Workaround

Adjust `prose_margin_bottom` until a suitable value is found where the content is displayed and no extra page is produced.
