### ISSUE TITLE
Allow theme to set font size and family of table cells

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#139]
The theme should be able to specify the font size and family of table cells. The font size and family used for the header row should be set separately.

```yaml
table:
  font_size: 12
  head:
    font_size: 10
    font_family: $heading_font_family
```

**Comment by mojavelinux** [comment]
The theme only supports one level of nesting currently, so it has to be written as:

```
table:
  font_size: $base_font_size_large
  head_font_size: $base_font_size_small
  head_font_family: $heading_font_family
```
