### ISSUE TITLE
Using Fallback font makes code line-height inconsistent

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1419]
# Test document 1

```
= test src
:pdf-style: test

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Maecenas feugiat fermentum pretium. Cras eu dolor imperdiet justo mattis
pulvinar. Cras nec lectus ligula. Proin elementum luctus elit, a tincidunt quam
facilisis non. Nunc quis mauris non turpis finibus luctus. Maecenas ante
sapien, sagittis quis accumsan in, `feugiat` quis sem. Praesent et auctor libero.


[source,sql]
--------
select * from mdm_out.party_masters where batch_id = ?;
select * from mdm_out.party_instance where batch_id = ?;
select * from mdm_out.id_document_masters where batch_id = ?;
select * from mdm_out.id_document_instance where batch_id = ?;
select * from mdm_out.add_name_masters where batch_id = ?;
select * from mdm_out.add_name_instance where batch_id = ?;
select * from mdm_out.contact_masters where batch_id = ?;
select * from mdm_out.contact_instance where batch_id = ?;
select * from mdm_out.address_masters where batch_id = ?;
select * from mdm_out.address_instance where batch_id = ?;
select * from mdm_out.loyalty_card_masters where batch_id = ?;
select * from mdm_out.loyalty_card_instance where batch_id = ?;
--------
```

# Test theme

`test-theme.yml`

```
font:
  catalog:
    Mono:
      normal: firamono-regular.ttf
      bold: firamono-bold.ttf
      italic: firamono-regular.ttf
      bold_italic: firamono-bold.ttf
      # normal: hack-regular.ttf
      # bold: hack-bold.ttf
      # italic: hack-italic.ttf
      # bold_italic: hack-bolditalic.ttf
      # normal: iosevka-regular.ttf
      # bold: iosevka-bold.ttf
      # italic: iosevka-italic.ttf
      # bold_italic: iosevka-bolditalic.ttf
    Fallback:
      normal: NotoSansSymbols2-Regular.ttf
      bold: NotoSansSymbols2-Regular.ttf
      italic: NotoSansSymbols2-Regular.ttf
      bold_italic: NotoSansSymbols2-Regular.ttf
  fallbacks:
  - Fallback

code:
  font_family: Mono
```

# PDF result

font Fira Mono:
![image](https://user-images.githubusercontent.com/234774/70025625-9cf4c080-15ae-11ea-8729-834a4f1e8621.png)

font Iosevka:
![image](https://user-images.githubusercontent.com/234774/70025666-bdbd1600-15ae-11ea-8924-3eff115666aa.png)

font Hack:
![image](https://user-images.githubusercontent.com/234774/70025707-e47b4c80-15ae-11ea-8d48-68c7f43626fd.png)

As you can see line height in code block is inconsistent.

# Removing Fallback font from theme

font Hack (the rest are the same OK)
![image](https://user-images.githubusercontent.com/234774/70025794-1be9f900-15af-11ea-8447-b32471711bd0.png)

**PS**

My main font is Noto Sans and it has a separate font that has all the symbols, so I kind of need it to be able to render checkboxes and other unicode symbols asciidoctor produces (some special spaces? Arrows?)

Noto Sans symbols font: https://github.com/googlefonts/noto-fonts/blob/master/hinted/NotoSansSymbols2/NotoSansSymbols2-Regular.ttf
