### ISSUE TITLE
Japanese doesn't show

### ISSUE THREAD

**Issue by dusicong** [asciidoctor/asciidoctor-pdf#1472]
Hi, there is a new problem here.
pdf file cannot show Japanese. 
![image](https://user-images.githubusercontent.com/20656749/71885027-d48df400-317c-11ea-9170-e45cfce5c01d.png)
I don't know if it is a common problem or not.

ruby:2.7.0
asciidoctor-pdf: 1.5.0.rc.1
asciidoctor-pdf-cjk-0.1.3 installed.
I also download asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1, but had a problem in downloading fonts according to https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic.

Any advice?

**Comment by mojavelinux** [comment]
By default, Asciidoctor PDF only bundles two themes. One theme references a subsetted font (NotoSerif) which only supports Western languages (English and most European languages). It also comes with a theme that references a subsetted font (M+ 1p) that includes a broad set of CJK characters, but not all. So I would start with trying the later theme:

```
asciidoctor-pdf -a pdf-theme=default-with-fallback-font document.adoc
```

If that doesn't work, what I recommend is making your own theme that references your own font. It's not difficult to dot that anymore. I don't think the asciidoctor-pdf-cjk-kai_gen_gothic is really necessary. See:

* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#language-overview
* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#custom-fonts
* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#modifying-the-font

**Comment by dusicong** [comment]
Thank you very much for the reply.
I will try your advice and tell you the result. :)

**Comment by dusicong** [comment]
Making my own theme seems to take a lot of time.
There is a time-saving solution.
downgrade to version 1.5.0.alpha.18, then problem solved.

Still don't understand why the new version can not work with Japanese (or CJK).

**Comment by mojavelinux** [comment]
> Still don't understand why the new version can not work with Japanese (or CJK).

This is not a true statement. The current version works the same way with Unicode as the previous version did. Likely there is an incompatibility in the configuration.

Please provide me with a sample document, an example which gems you are using, and a copy of your theme so that I can see what you might be doing wrong.

**Comment by mojavelinux** [comment]
I'd say it looks pretty great with the default-with-fallback-font theme.

Here's sample input:

```
Anypoint Security は、多層的アプローチでアプリケーションネットワークを保護します。これらのレイヤは連携し、API へのアクセスを制御したり、ポリシーを適用したり、すべてのインバウンドトラフィックまたはアウトバウンドトラフィックをプロキシしたりして、アプリケーションネットワークとネットワークの個々のノードの両方を保護します。これにより、外部の脅威や攻撃が軽減されます。Anypoint Security には、ネットワーク実装に高い負荷をかけずに攻撃を検出してトラフィックを検証する専用のエンドポイントが用意されています。

== ポリシー

Anypoint Security の特徴として、Runtime Fabric にデプロイされているすべてのノードにポリシーを適用する、パフォーマンス、信頼性、拡張性の高いサービスが挙げられます。その後、Anypoint Security ポリシーは、すべてのトラフィックが通過するデフォルトのファイアウォール/ルータ機能として動作します。

== シークレットマネージャ

Anypoint Security には、デプロイメントで使用される TLS 証明書とキーストアを保存するセキュアコンテナが用意されています。シークレットマネージャを使用すれば、Runtime Fabric へのインバウンドトラフィックを暗号化する TLS コンテキストをセットアップするために必要なシークレットを保存できます。

== トークナイゼーションサービス

Anypoint Security のトークナイゼーションサービスでは、クレジットカード番号などのキー値をトークンに置き換えて機密データの不必要な漏洩を保護します。
```

Here's how you'd run it:

```
asciidoctor-pdf -a scripts=cjk -a pdf-theme=default-with-fallback-font jp.adoc
```

The `-a script=cjk` is important because it tells the converter to put semantic breaks in lines to accommodate mixing of English and Japanese.

Are you seeing different results?

**Comment by mojavelinux** [comment]
I also used the KaiGenGothicJP theme from the asciidoctor-pdf-cjk-kai_gen_gothic gem, and it worked decently:

```
asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-theme=KaiGenGothicJP jp.adoc
```

Note the absence of the `-a scripts=cjk` in that case. That's because that theme already adds the semantic breaks.

**Comment by mojavelinux** [comment]
If you want to install the asciidoctor-pdf-cjk-kai_gen_gothic gem to get the fonts, but then use your own theme. Here's how you'd do it:

1. Install the gem:

       $ gem install asciidoctor-pdf-cjk-kai_gen_gothic

2. Get the fonts:

       $ asciidoctor-pdf-cjk-kai_gen_gothic-install

3. Create a theme that extends default:

   ```yml
   extends: default
   font:
     catalog:
       KaiGen Gothic JP:
         normal: KaiGenGothicJP-Regular.ttf
         bold: KaiGenGothicJP-Bold.ttf
         italic: KaiGenGothicJP-Regular-Italic.ttf
         bold_italic: KaiGenGothicJP-Bold-Italic.ttf
       M+ 1mn:
         normal: GEM_FONTS_DIR/mplus1mn-regular-subset.ttf
         bold: GEM_FONTS_DIR/mplus1mn-bold-subset.ttf
         italic: GEM_FONTS_DIR/mplus1mn-italic-subset.ttf
         bold_italic: GEM_FONTS_DIR/mplus1mn-bold_italic-subset.ttf
     fallbacks:
     - KaiGen Gothic JP
   base:
     font-family: KaiGen Gothic JP
   heading:
     font-family: $base-font-family
   abstract:
     title:
       font-family: $heading-font-family
   sidebar:
     title:
       font-family: $heading-font-family
   ```

4. Load your theme when running Asciidoctor PDF:

       $ asciidoctor-pdf -a scripts=cjk -a pdf-theme=./jp-theme.yml -a pdf-fontsdir=$(dirname $(gem which asciidoctor-pdf-cjk-kai_gen_gothic))/../data/fonts jp.adoc

   or

       $ asciidoctor-pdf -a scripts=cjk -a pdf-theme=./jp-theme.yml -a pdf-fontsdir=$(ruby -r asciidoctor-pdf-cjk-kai_gen_gothic -e "puts File.expand_path '../fonts', (Gem.datadir 'asciidoctor-pdf-cjk-kai_gen_gothic')") jp.adoc

I'd be happy to add this info the theming guide.
