### ISSUE TITLE
Allow custom theme to extend font catalog

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1505]
Currently, the font catalog defined in the custom theme replaces any previously defined font catalog. This means that to add a new font, you have to declare all the existing fonts again. It would be nice if it were possible to configure the font catalog to be merged with the existing font catalog.

For example, to define a fallback font for the default theme, you could use:

```yml
extends: default
font:
  catalog:
    merge: true
    VLGothic:
      normal: &VLGothic /usr/share/fonts/vlgothic/VL-Gothic-Regular.ttf
      bold: *VLGothic
      italic: *VLGothic
      bold_italic: *VLGothic
  fallbacks:
  - VLGothic
```

The addition here is `merge: true`. That tells the theme loader to merge the new entries into the existing entries (only replacing an existing font if the name matches).
