### ISSUE TITLE
Nested unordered list not showing properly with custom font

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-pdf#1560]
I am using a custom font in my PDF theme, but nested lists are not showing correctly. Suppose I have this asciidoc:

```
* Level 1a
* Level 1b
** Level 2
*** Level 3
** Level 2b
```

This renders fine by default:
![image](https://user-images.githubusercontent.com/1115823/74764983-08336200-5283-11ea-84b1-56e0b03c4f3e.png)

But renders like this using my custom font:
![image](https://user-images.githubusercontent.com/1115823/74765010-16817e00-5283-11ea-9315-365dc21fa7e5.png)

The custom font is `Open Sans`, which is specified like this in the theme:

```
extends: default
font:
  catalog:
    Noto Serif:
      normal: GEM_FONTS_DIR/notoserif-regular-subset.ttf
      bold: GEM_FONTS_DIR/notoserif-bold-subset.ttf
      italic: GEM_FONTS_DIR/notoserif-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/notoserif-bold_italic-subset.ttf
      # M+ 1mn supports ASCII and the circled numbers used for conums
    M+ 1mn:
      normal: GEM_FONTS_DIR/mplus1mn-regular-subset.ttf
      bold: GEM_FONTS_DIR/mplus1mn-bold-subset.ttf
      italic: GEM_FONTS_DIR/mplus1mn-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/mplus1mn-bold_italic-subset.ttf
    OpenSans:
      normal: opensans-normal.ttf
      italic: opensans-italic.ttf
      bold: opensans-bold.ttf
      bold_italic: opensans-bold_italic.ttf
    Rokkitt:
      normal: rokkitt-normal.ttf
      bold: rokkitt-bold.ttf
base:
  font_family: OpenSans
heading:
  font_family: Rokkitt
  font_style: normal
```

Is this a font problem? Or is it the PDF rendering? Is there any known workaround?

UPDATE:
If I copy the text from the PDF to Pages, then the squares are converted into the proper circles. I can also change the font to Open Sans there and the circles remain properly shown.

**Comment by mojavelinux** [comment]
This is an indication that the font you have selected (in this case Rokkitt) does not provide the requisite glyphs as described in the [theming guide](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#modifying-the-font). The box you see is the fallback glyph when a glyph is missing for a character.

You can get a list of which characters are missing by running asciidoctor-pdf with the `-v` flag.

There are three solutions to this problem:

1. Update the font to include the missing glyphs (which you can do by opening the font in fontforge and copying the glyph from another character).
2. Configure the provided fallback font (M+ 1p) in your theme, like the built-in default-with-fallback-font theme
3. Reconfigure the characters used for bullets. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-ulist-marker-type

**Comment by mojavelinux** [comment]
Here's the quickest way to enable the fallback font:

```
extends: default-with-fallback-font
font:
  catalog:
    merge: true
    OpenSans:
      normal: opensans-normal.ttf
      italic: opensans-italic.ttf
      bold: opensans-bold.ttf
      bold_italic: opensans-bold_italic.ttf
    Rokkitt:
      normal: rokkitt-normal.ttf
      bold: rokkitt-bold.ttf
base:
  font_family: OpenSans
heading:
  font_family: Rokkitt
  font_style: normal
```
