### ISSUE TITLE
Recognize * key as a shorthand for all variants in font catalog

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1588]
It's currently possible to assign a single font file to all font variants using the following shorthand:

```yaml
Font Name: path/to/font.ttf
```

However, if you want to use a different font file for just one of the styles, then you need to go back to specifying each font variant individually. It should be possible to use the `*` key as a shorthand for all variants. Then, you can override the font file for just a single variant.

```yaml
Font Name:
  '*': path/to/font.ttf
  bold: path/to/bold-font.ttf
```
