### ISSUE TITLE
unable to change pagination position (too close from page border)

### ISSUE THREAD

**Issue by zpartakov** [asciidoctor/asciidoctor-pdf#1602]
Hi

I'm trying to use asciidoctor-pdf for a non profit literary association publication chain (asciidoc->html, epub and pdf), [éditions moinsdecent](https://moinsdecent.net), and it's really great

but...

I have an issue regarding the position of the page number, which is too close from the page border, therefore not printable.

Here is an example:
[radioaktif15.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/4322438/radioaktif15.pdf)

You may see on the right bottom the page number "15"
Tried many things on the .yml file without any success, hereby (commented lines after l42)

```
page:
  layout: portrait
  margin: [2cm, 2cm, 2cm, 2cm]
  #size: Letter
  #task novel format
  size: [11cm,18cm]
font:
  catalog:
    FreeSerif:
      normal: FreeSerif.ttf
      italic: FreeSerifItalic.ttf
      bold: FreeSerifBold.ttf
      bold_italic: FreeSerifBoldItalic.ttf
base:
  font-color: #333333
  font-family: FreeSerif
  font-size: 9
  align: justify
  #tryes to get hyphenation in french, without success
  #hyphenation: auto
  #hyphens: auto;
  #word-wrap: normal
  #word-wrap / breakword css3 / hyphenation
  #word-wrap: normal|break-word|initial|inherit; ? auto
  #word-break: normal / break-all;
  #word-wrap: normal
  #word-break: break-all
  line-height-length: 10
  line-height: $base-line-height-length / $base-font-size
vertical-spacing: $base-line-height-length
heading:
  font-color: #262626
  font-size: 15
  font-style: bold
  line-height: 1
  margin-bottom: $vertical-spacing
link:
  font-color: #002FA7
outline-list:
  indent: $base-font-size * 1.5
footer:
  #try to move the page numbering without success
  #page-number:
  #margin: [2cm,2cm,2cm,2cm]
  #margin-bottom: 2cm
  height: $base-line-height-length * 2.5
  line-height: 1
  #margin: [0cm,2cm,0cm,0cm]
  recto:
    right:
      content: '{page-number}'
  verso:
    left:
      content: $footer-recto-right-content
```

Any clue please?

**Comment by mojavelinux** [comment]
Correct me if I'm wrong, but I assume what you mean is that the page number is too close to the bottom of the page. That can be adjusted.

Your page margin is 2cm. Typically, you want your running content height to match this value. So first, you'd set the height of the footer to 2cm.

```yml
footer:
  height: 2cm
  ...
```

If you want to see the area that the footer takes up, you can shade the background temporarily.

```yml
footer:
  height: 2cm
  background-color: #CCCCCC
```

By doing that, you can see that the number is not quite at the top of the box. That's because there is a padding applied by default. You can remove that:

```yml
footer:
  height: 2cm
  padding: 0
  ...
```

Now the page number should be plenty far from the edge of the page. But you can continue to make adjustments.

For more info, refer to the theming guide for the running content: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-footer

(Keep in mind that while the theme looks like CSS, it's not CSS. It's just inspired by CSS).
