### ISSUE TITLE
Add support for normal italic style

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#1603]
When the bold style is present in the set of inherited styles, there's no way to apply italic without making it bold italic. Add a `normal_italic` font style that can be used to reset the inherited bold style and apply only italic.

Example:

```yml
role:
  subtitle:
    font_style: normal_italic
```
