### ISSUE TITLE
heading font-size key only works when using underscore instead of dash

### ISSUE THREAD

**Issue by astrograph** [asciidoctor/asciidoctor-pdf#1635]
I was only able to change the heading sizes in the PDF output when I used   h6_font_size instead of  h6-font-size.

The documentation: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-heading shows dash instead of underscore when using the font-size key.

in the end this worked for me: 

```
heading:
  h1_font_size: 32
  h2_font_size: 24
  h3_font_size: 18
  h4_font_size: 16
  h5_font_size: 14
  h6_font_size: 12
```

**Comment by mojavelinux** [comment]
Can you please describe how you are defining your theme? Where are you defining it? How are you loading it?

**Comment by mojavelinux** [comment]
My tests and the test suite show that this scenario is supported. However, the one case it is not supported is if you are modifying the default theme from the gem (because the keys do not receive special processing in that file).

Here's how to define it in a way that works:

**my-theme.yml**

```yml
extends: default
heading:
  h3-font-size: 40
```
