### ISSUE TITLE
running-content: start-at: has no effect

### ISSUE THREAD

**Issue by clydebarrow** [asciidoctor/asciidoctor-pdf#1643]
Using asciidoctor-pdf 1.5.3 I have this in my theme:

````
header:
  height: $base-line-height-length * 2.5
  line-height: 1
  recto:
    left:
      content: '{doctitle}'
    right:
      content: 'Document {docnumber} revision {revnumber}'
  verso:
    right:
      content: $header-recto-left-content
footer:
  height: $base-line-height-length * 2.5
  line-height: 1
  recto:
    left:
      content: '{revdate}'
    right:
      content: 'Page {page-number} of {page-count}'
  verso:
    left:
      content: $footer-recto-right-content
    right:
      content: $footer-recto-left-content
running-content:
  start-at: 2
````
But the header and footer appear on page 1. I also tried using `toc` instead of `2` but no change. Leaving out the `start-at` directive (which according to the docs should default to `body`) also has no effect - the header and footer still appear on all pages.

**Comment by mojavelinux** [comment]
Please provide a sample AsciiDoc file that exhibits this problem.

**Comment by clydebarrow** [comment]
Attached. I had to zip it, .adoc files are not allowed :-(
[test.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/4465849/test.zip)

**Comment by mojavelinux** [comment]
Aha. Currently, the start_at settings for running content and page numbering only apply if you're using a title page.

I encourage you to use a title page rather than the current approach of inserting hard breaks. You can customize the lines in the start page using the authors key: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-authors

For example:

```yml
extends: default
title-page:
  align: center
  title:
    top: 0%
  authors:
    margin-top: 2in
    content: |
      Document number {docnumber}
      Revision {revnumber}
      Date {revdate}

      Acme
      Ltd.

      Copyright (C) 2017-2020 Acme Ltd
  revision:
    display: none
```

Then your AsciiDoc would look like this:

```
= Sample file
Blah blah blah
6, 2020-04-11
:title-page:
:xrefstyle: short
:sectnums:
:docnumber: 2456-05
:toc: macro

.Revision History
[cols="4,2,10"]
|===
|Date |Revision |Document Changes

|2017-02-17 |1 |Initial Draft
|2020-04-11 |6|Sample file
|===

<<<

toc::[]

== Introduction

=== The Into

Blah blah blah
```

As a general rule, you should avoid putting formatting instructions in your AsciiDoc content. Leverage the capabilities of the converter instead to get the typesetting you want.
