### ISSUE TITLE
List Items inside of a table with inline code overlap

### ISSUE THREAD

**Issue by chuck-confluent** [asciidoctor/asciidoctor-pdf#1650]
![image](https://user-images.githubusercontent.com/48225759/79515840-8a7ba080-7ffe-11ea-9cd7-66a93acd3006.png)

I have a couple of spots in my document where I have a two column table with list items inside. When inline code wraps to the next line, I get some strange overlapping.

I thought this might be a misconfiguration in my theme, but I looked at a previous version where this overlap didn't occur and the theme for `outline_list` is the same.

I hope it's some misconfiuration, but I fear it's a bug in a newer version of asciidoctor-pdf. The older document was made using 1.5.0.beta.2, whereas the newer document is using 1.5.3

**Comment by mojavelinux** [comment]
It looks like it is specific to your theme or font, likely due to new line height logic that was added to address other bugs. It may have something to do with https://github.com/asciidoctor/asciidoctor-pdf/issues/1419#issuecomment-561028473

Can you provide a reproducible example so that I can study it?

**Comment by chuck-confluent** [comment]
Ok I just re-ran with the same exact theme 1.5.0.beta.2 and the issue did not occur

**Comment by mojavelinux** [comment]
Can you test using the default theme in Asciidoctor PDF?

**Comment by chuck-confluent** [comment]
Here's some asciidoc that should be illustrative:

```
== breaking stuff

[cols="a,a",grid=none,frame=none]
|===
|First column

* A bullet point with some `code` and more `really long code to go to next line` and maybe `more code`

| Another column

* Stuff
|===
```

**Comment by chuck-confluent** [comment]
Damn, actually I just ran with the default theme and the issue did not occur. This is a misconfiguration on my part, but I'm not sure where. Here is my slide theme:

```yml
# First page of document
title_page:
  background-color: #173361
  logo:
    image: image:confluent_logo-white.png[pdfwidth=80%]
    top: 40%
    align: center
  align: left
  title:
    top: 6%
    font:
      size: 36
      family: MarkOT
      style: bold
      color: #FFFFFF
  subtitle:
    margin_top: 10
    font_size: 18
    font_color: #FFFFFF
    line_height: 1.1
  authors:
    margin_top: 70  
    font:
      size: 12
      family: MarkOT
      style: bold
      color: #FFFFFF
  revision:
    font_color: #FFFFFF
    style: light

# With title, footers, margins, shoot for 1335x645 res images 
page:
  size: [21.42cm, 38.1cm]
  layout: landscape
  margin: [0.35in,0.35in,0.35in,0.35in]

base:
  align: left
  font_size: 24
  font_color: #000000
  font_family: MarkOT
  line_height_length: 16
  line_height: $base_line_height_length / $base_font_size

vertical_spacing: $base-line-height-length
vertical_rhythm: $base_line_height_length

prose:
  margin_top: 0
  margin_bottom: $vertical_spacing

link:
  font_color: #0074A2
  text-decoration: underline

verse:
  text_indent: 50

# callout numbers in code, like <<1>>
conum:
  line_height: 1.15

sidebar:
  background_color: #eeeeee
  padding: [12, 12, 0, 12]
  title_align: left
  font_style: normal
  font_size: 16
  border-radius: 10

# The different title sizes (=, ==, ===, etc.)
heading:
  h1:
    font_color: #1B3461
    font_size: 48
    font_style: bold
  h2:
    font_color: #1B3461
    font_size: 30
    font_style: bold
  h3:
    font_color: #1B3461
    font_size: 28
    font_style: normal
  h4:
    font_color: #1B3461
    font_style: light
    font_size: 24
  h5:
    font_color: #1B3461
    font_size: 14
    font_style: bold
  h6:
    font_color: #1B3461
    font_size: 9
    font_style: bold
  h7:
    font_color: #646464
    font_size: 9
    font_style: normal

# Example block (====)
example:
  border_color: #829494
  background_color: #B4E1E4
  border_width: 1
  padding: [12, 12, 0, 12]
  font_style: normal
  font_size: 12

# NOTE, TIP, IMPORTANT, CAUTION, WARNING
admonition:
  icon:
    tip:
      stroke-color: #FFC40C
    warning:
      stroke-color: #F26135
    important:
      stroke-color: #D8365D
    caution:
      stroke-color: #D8365D
    note:
      stroke-color: #00AFBA
  column_rule_color: #E6F5FB
  border_color: #E6F5FB
  border_width: 0.5
  padding: [9, 9, 9, 9]

# Code blocks
code:
  background_color: #FAFAFA
  border_color: #F2F2F2
  font_family: SourceCodePro
  font_size: 16
  line_height: 1.5
  padding: 9
  border_width: 0.5

# Inline code
literal:
  background_color: #f9f2f4
  border_color: #F2F2F2
  font_color: #c7254e
  font_family: SourceCodePro
  font_size: 18

thematic_break:
  border_color: #bebebe
  border_style: solid
  border_width: 0.5
  margin_top: 25
  margin_bottom: 40

# ulist:
#   marker:
#     font_family: NotoSansFallback
#     font_size: 24
#     line_height: 1.5
#     font_color: #0074A2
#     disc:
#       content: "\u2022"
#       font_color: #0074A2

description_list:
  term_font_style: bold
  term_spacing: 4
  description_indent: 25

outline_list:
  indent: 20
  item_spacing: 8
  marker_font_color: #0074A2

abstract:
  font_color: #4597CB
  font_size: 9
  font_style: Bold
  title:
    align: left
    font_color: #4597CB
    font_size: 12
    font_style: bold

table:
  background_color: #ffffff
  border_color: #bebebe
  border_width: 0.5
  caption_side: top
  font_size: 20
  grid_color: #F2F2F2
  head:
    font_size: 24
    font_style: bold
    background_color: #B4E1E4
    font_color: #173361
  foot:
    background_color: #4597CB
    font_color: #ffffff
  body:
    background_color: #FFFFFF
    stripe_background_color: #E6F5FB
  cell:
    padding: 4
toc:
  dot_leader:
    font_color: #bebebe
  line-height: 1.5
  h2:
    font_color: #003B49
    font_size: 12
    font_style: bold
  h3:
    font_color: #4597CB
    font_size: 9
    font_style: bold
  h4:
    font_color: #4b4b4b
    font_size: 9
    font_style: normal

footer:
  height: 0.5in
  font_color: #829494
  font_size: 12
  line_height: 1
  recto:
    left:
      content: '© 2014-2020 Confluent, Inc. '
    right:
      content: |
        {chapter-title} +
        {page-number}
    center:
      content: 'Not to be reproduced in any form without prior written consent.'
  verso:
    left: 
      content: $footer_recto_left_content
    center: 
      content: $footer_recto_center_content
    right: 
      content: $footer_recto_right_content

image:
  align: center
caption:
  align: left
  font_size: $base_font_size * 0.95
  font_style: italic

font:
  catalog:
    Noto Serif:
      normal: GEM_FONTS_DIR/notoserif-regular-subset.ttf
      bold: GEM_FONTS_DIR/notoserif-bold-subset.ttf
      italic: GEM_FONTS_DIR/notoserif-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/notoserif-bold_italic-subset.ttf
    MarkOT:
      normal: MarkOT-Light.ttf
      italic: MarkOT-Italic.ttf
      bold: MarkOT-Bold.ttf
      bold_italic: MarkOT-BoldItalic.ttf
      light: MarkOT-Light.ttf
      medium: MarkOT-Medium.ttf
    SourceCodePro:
      normal: SourceCodePro-Regular.ttf
      italic: SourceCodePro-It.ttf
      bold: SourceCodePro-Bold.ttf
      bold_italic: SourceCodePro-BoldIt.ttf
      Medium: SourceCodePro-Medium.ttf
      Medium_italic: SourceCodePro-MediumIt.ttf
    NotoSansFallback:
      normal: NotoSans-Regular.ttf
      italic: NotoSans-Italic.ttf
      bold: NotoSans-Bold.ttf
      bold_italic: NotoSans-BoldItalic.ttf
  fallbacks:
    - NotoSansFallback
```
