### ISSUE TITLE
Index term gets double space or extra padding-left?

### ISSUE THREAD

**Issue by peterjaap** [asciidoctor/asciidoctor-pdf#1672]
I have the following text;

```
From Laravel's perspective, a model is an _Eloquent_ model. ((Eloquent)) is an Object Relational Mapper (ORM) (((Object Relational Mapper,ORM))) built specifically for ((Laravel)) but is useful in any PHP application. It ties a model to a corresponding table using a simple ((ActiveRecord)) pattern and offers a ((fluent API)).
```

In my theme, I use the MinionPro font, which I defined like this;

```yaml
font:
  catalog:
    merge: true
    MinionPro:
      regular: MinionPro/MinionProRegular.ttf
      italic: MinionPro/MinionProItalic.ttf
      bold: MinionPro/MinionProBold.ttf
      bold_italic: MinionPro/MinionProBoldItalic.ttf

base:
  font:
    family: MinionPro
    size: 12
    color: #303030
```

When I generate my PDF, this is my output. You can see that the index terms have extra whitespace preceding them.

![image](https://user-images.githubusercontent.com/431360/80576467-88094580-8a05-11ea-8c18-a7ede42553c5.png)

As you can see, this also happens when using concealed index terms.

Here is the copy/pasted text;

```
From Laravel’s perspective, a model is an Eloquent model. Eloquent is
an Object Relational Mapper (ORM) built specifically for Laravel but is
useful in any PHP application. It ties a model to a corresponding table
using a simple ActiveRecord pattern and offers a fluent API.
```

I also ran this copy/pasted text through [a tool](https://www.babelstone.co.uk/Unicode/whatisit.html) to check whether the space is a weird unicode character but it appears to be a normal space (`U+0020 : SPACE [SP]`).

I also can't find anything controlling this behavior in the theming/styling docs. It doesn't happen when using other fonts so I think it might be font-related but I don't know how or why. This is what it looks like with the default font;

![image](https://user-images.githubusercontent.com/431360/80576297-395bab80-8a05-11ea-8892-72b9cf6f4616.png)
