### ISSUE TITLE
Text is not printed on page header with gem version 1.5.3

### ISSUE THREAD

**Issue by xu4wang** [asciidoctor/asciidoctor-pdf#1676]
I noticed there was an issue for this, and it was fixed.
https://github.com/asciidoctor/asciidoctor-pdf/issues/1087

However, I'm facing the same issue, my asciidoctor-pdf is with below version:

```
WangXus-MacBook-Pro:github wangxu$ asciidoctor-pdf -V
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

```

The theme file I am using:

```
extends: default
header:
  padding: [0.35in, 0, 0, -0.35in]
  height: 1in
  vertical-align: center
  line-height: 1
  recto:
    center:
      content: '(C) xxx -- v{revnumber}, {docdate}'
  verso:
    center:
      content:  '(C) xxx -- v{revnumber}, {docdate}'
footer:
  height: 0.75in
  line-height: 1
  recto:
    right:
      content: '{section-or-chapter-title} | *{page-number}*'
  verso:
    left:
      content: '*{page-number}* | {chapter-title}
```

The footer is displayed, the header is empty on the generated pdf.
