### ISSUE TITLE
Add support for theming admonition blocks by type

### ISSUE THREAD

**Issue by Hamsterbau** [asciidoctor/asciidoctor-pdf#1685]
### Current behaviour

Currently if i want to use asciidoc pdf generator with theming, it is possible (thanks to another issue) to change basic stuff for admonition blocks:
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-admonition

**Example:**
``` yml
admonition:
  background_color: f5f5f5
  border_color: 7d7d7d
  border_width: $base_border_width
  padding: [0, $horizontal_rhythm, 0, $horizontal_rhythm]
```

**Issue:**
https://github.com/asciidoctor/asciidoctor-pdf/issues/444

But i cannot change these settings (especially background color) for a specific block type (e. g. _caution_ in red or _warning_ in orange).

### Improvement: Admonition settings based on type

It would be nice to be able to configure admonition settings based on the current type.

**Example:**

``` yml
admonition:
  caution:  
    background_color: ff0000
    border_color: ff0000
  warning:  
    background_color: ffa500
    border_color: ffa500
```

**Comment by mojavelinux** [comment]
Here's how you can implement this using an extended converter.

```rb
class PDFConverterAdmonitionThemePerType < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def convert_admonition node
    type = node.attr 'name'
    key_prefix = %(admonition_#{type}_)
    return super if (entries = theme.each_pair.select {|name, val| name.start_with? key_prefix }).empty?
    save_theme do
      entries.each {|name, val| theme[%(admonition_#{name.to_s.delete_prefix key_prefix})] = val }
      super
    end
  end
end
```

It works by temporarily overlaying the theme keys for a specific type onto the main admontion theme keys.

**Comment by mojavelinux** [comment]
This is going to be tricky to support by default since the admonition keys are a bit inconsistent. Both the label and icon can be configured per type, except the type comes after the element in the key name. Ideally, we would switch this all around so that the type is always the second segment of the key.

```yml
admonition:
  border-width: 0.5
  tip:
    border-color: #FFFF00
    icon:
      name: far-lightbub
    label:
      font-style: italic
```

Making that change would warrant a major version bump.

I'm also wondering whether the type should be in all uppercase so it is not confused with other key names.

```yml
admonition:
  TIP:
    border-color: #FFFF00
```
