### ISSUE TITLE
Usage of "numbering-start-at" unclear. 

### ISSUE THREAD

**Issue by saschakr** [asciidoctor/asciidoctor-pdf#1710]
Hello everybody,

I've waited for [Pull#1649](https://github.com/asciidoctor/asciidoctor-pdf/pull/1649) because I need to start my page numbering on page 2 (with number 2), but this is a little unclear to me.

I've made following example.

**page.adoc**
```
= Testpage
:toc: macro
:sectnums:

<<<
toc::[]
<<<
== page one
<<<
== page two
<<<
== page three
```

**theme.yml**
```
extends: default

running-content:
  start-at: 2

page:
  numbering-start-at: 2

header:
  height: 0.75in
  line-height: 1.2
  recto:
    center:
      content: '{page-number}'
  verso:
    center:
      content: '{page-number}'
```

I would except my page numbering starts on page 2 with number 2 but it is still on page 1.
It would work if I set the `:title-page: true` within the adoc file, but I need to customize it too much.

So my question is: What am I doing wrong? Did I misunderstood the pull  #request?

EDIT:

```
asciidoctor-pdf --version
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
