### ISSUE TITLE
Ulist bullet alignment

### ISSUE THREAD

**Issue by daveshook** [asciidoctor/asciidoctor-pdf#1720]
With unordered lists, the bullet for the initial list level is located against the left margin. I would like it to be centered under the first character of the preceding normal text. I have tried to use `padding` to accomplish this to no avail. Is there a way to move the bullet symbol slightly to the right?

**Comment by mojavelinux** [comment]
The theming system does not give you control over the alignment of the bullet. However, you can adjust the amount of indentation applied to the list. I find that if I use the following setting, the bullet appears at the location you describe:

```
outline_list:
  indent: $base_font_size
```

Here's how that looks:

![bullet-alignment](https://user-images.githubusercontent.com/79351/86285140-52b5db00-bba1-11ea-830a-5a202ab0ec04.png)

Beyond that, the theming system does not provide that degree of control.

**Comment by daveshook** [comment]
That did the trick. Thanks!

**Comment by mojavelinux** [comment]
Woot!

**Comment by daveshook** [comment]
What controls the position of the item number in a outline list? I expected that the number would line up similarly to the bullet in the unordered list. That isn't the case though. See the attached image for what the following theme control statements build.
```
outline_list:
  indent: $base_font_size * 1.05
  item_spacing: 8
  marker_font_color: #0074A2

ulist:
  marker:
    font_family: NotoSansFallback
    font_size: 24  
    font_color: #0074A2
    disc:
      content: "\u2022"
      font_color: #0074A2
```
![_sample](https://user-images.githubusercontent.com/45415767/86369337-4a66aa00-bc4c-11ea-8bf2-16138cfcb59c.png)
