### ISSUE TITLE
font in pdf table cell

### ISSUE THREAD

**Issue by mariomuja** [asciidoctor/asciidoctor-pdf#1744]
I am using asciidoctor-pdf and would like to use a custom font in a particular table cell and another font and font size in other cells of the same table. Is this possible? I create the pdf using the following command line

asciidoctor-pdf -a pdf-themesdir=. -a pdf-theme=my.yml -a pdf-fontsdir=./fonts my.adoc

If it is not possible with asciidoctor-pdf, would it be possible using asciidoctor.js (using it as a node.js app and formatting with CSS instead of YML)?

any help appreciated,
Mario

This is MY.YML 

```
font:
  catalog:
    Futura PT Book:
      normal: ftn45.ttf
      bold: ftn45.ttf
      italic: ftn46.ttf
      bold_italic: ftn46.ttf
      
    Futura PT Demi:
        normal: ftn65.ttf
        bold: ftn65.ttf
        italic: ftn66.ttf
        bold_italic: ftn66.ttf

grey:
  background_color: grey
  
page:
  background_color: ffffff
  layout: landscape
  margin: [0.57in, 0.57in, 0.57in, 0.8in]
  size: A4

base:
  align: left
  vertical_align: top
  font_family: Futura PT Book
  font_size: 10
  line_height_length: 10
  line_height: $base_line_height_length / $base_font_size
  font_size_large: 16
  font_size_small: 8
  font_size_min: 8
  font_style: normal
  border_color: eeeeee

link:
  font_color: 428bca

heading:
  align: left  
  font_family: Futura PT Demi
  font_style: normal
  h1_font_size: $base_font_size_large
  h2_font_size: $base_font_size
  h3_font_size: $base_font_size_small
  line_height: 1

caption:
  vertical_align: top
  font_family: Futura PT Demi
  line_height: 1

lead:
  margin: 0
  font_family: Futura PT Demi
  font_size: $base_font_size_large
  line_height: 1

table:
  cell_padding: [5,25,5,5]

header:
  height: 1.2in
  padding: [50, 10, 15, 10]
  recto:
    right:
      content: image:.\\images\\test.png[width=40]
  verso:
    right:
      content: $header_recto_right_content

footer:
  font-size: $base_font_size
  font-color: #C6C6C6
  height: 1.2in
  line_height: 1
  vertical_align: bottom
  padding: [5, 10, 15, 10]
  recto:
    left:
      content: |
        test +
        test
    right:
      content: '{page-number} / {page-count}'
  verso:
    left:
      content: $footer_recto_left_content
    right:
      content: $footer_recto_right_content
```
