### ISSUE TITLE
Allow margin to be set per heading level

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#176]
Like with other heading properties in the theme, allow the margin to be set per heading level with a fallback to the margins set on the heading key.

Example:

```
heading:
  margin_top: 2.4
  margin_bottom: 9.6
  h1_margin_top: 0
  h1_margin_bottom: 12
```

To solve this, the `theme_margin` method should accept a level argument like `theme_font`.
