### ISSUE TITLE
Callouts don't render correctly in version 1.5.4

### ISSUE THREAD

**Issue by cdeyoung** [asciidoctor/asciidoctor-pdf#1878]
Using # <1> to render callouts doesn't work correctly in asciidoctor-pdf 1.5.4. For example, the following code:

```
"Hello, World!"    # <1>
```

Should output:

```
"Hello, World!"  ①
```

But instead outputs:

```
"Hello, World!"  ¬
```

This works correctly in 1.5.3 but is broken in 1.5.4.

**Comment by mojavelinux** [comment]
Tests confirm that when using the default theme, the callout numbers inside verbatim blocks do work. So it must be that when you upgraded, something in your configuration became incompatible. (Though I can't see anything between 1.5.3 and 1.5.4 that would have caused this).

Note that in 1.5.4, the font family for callout numbers is controlled by the `conum` category key. Please check this key in your theme file (assuming you are using one) to verify it has the right settings. Here's what the default theme specifies:

```yml
conum:
  font_family: $literal_font_family
  font_color: $literal_font_color
  font_size: $base_font_size
  line_height: 4 / 3
  glyphs: circled
```
