### ISSUE TITLE
Set paragraph vertical margin to 0

### ISSUE THREAD

**Issue by PeterSchmeichel** [asciidoctor/asciidoctor-pdf#1926]
It should be possible to have ordinary paragraphs without an empty line between them.
But nothing seems to work.

Example:

```
base:
  font_family: Calibri
  font_color: #333333
  line_height_length: 11
  font_size: 11
  margin_bottom: 0
  margin_top: 0
  margin-inside: 0
  margin-outside: 0
  vertical_spacing: 0
  border-width: 0
```

This should result in two paragraphs having no empty line between them, but doesn't.

**Comment by mojavelinux** [comment]
This can be accomplished using a combination of margin-inner and (optionally) text-indent on the prose key.

```yml
extends: default
prose:
  margin-inner: 0
  text-indent: 0
```

See https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#prose

Please ask questions such as this one in the community chat at https://asciidoctor.zulipchat.com.
