### ISSUE TITLE
Add Option to hide the title, but keep it in the meta information

### ISSUE THREAD

**Issue by ModProg** [asciidoctor/asciidoctor-pdf#1942]
I would like to not use a title (I could do that by omitting `= Title` at the top) but I still want the File to have a Title to show up, for example in the Browser tab.

**Comment by ModProg** [comment]
For now I'm gonna do this:
```yml
heading:
  h1-font-color: [255,255,255]
  h1-font-size: 0
```
