### ISSUE TITLE
Document header not shown if undefined placeholders are used

### ISSUE THREAD

**Issue by david0** [asciidoctor/asciidoctor-pdf#1948]
Looks like the asciidoctor-pdf will not print the header at all if placeholders are used that are not defined.

Wouldn't it be better to use an empty string for placeholders that could not be replaced?

e.g.
```yaml
extends: default
header:
  height: $base_line_height_length * 3
  verso:
    left: 
      content: '{doctitle} {version}'
```

```asciidoctor
:pdf-style: theme.yml
= Title

<<<

second page
```

Will render as:
![grafik](https://user-images.githubusercontent.com/1685610/125294244-66ebf680-e324-11eb-99ef-12d7728c2cb3.png)

instead of (my expectation):
![grafik](https://user-images.githubusercontent.com/1685610/125294186-5b003480-e324-11eb-8136-4b3354a30601.png)

**Comment by mojavelinux** [comment]
No, this design is intentional.

> If you reference an attribute which is not defined, all the text on that same line in the running content will be dropped. This feature allows you to have alternate lines that are selected when all the attribute references are satisfied.
> https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#attribute-references

If you want to ensure the running content is always displayed, then you need to include at least one line in which all attributes are resolved. Here's an example:

```yaml
header:
  verso:
    left: 
      content: |
        {blank}
        {doctitle} {version}
```

or

```yaml
header:
  verso:
    left: 
      content: |
        {doctitle}
        {version}
```

I'm not entertaining a proposal to change this design right now.
