### ISSUE TITLE
Sans Serif font, which includes all common characters

### ISSUE THREAD

**Issue by Palexer** [asciidoctor/asciidoctor-pdf#1955]
Is there a known font, that can display things like arrows, multiple levels of list bullet points, special 'versions' of characters like a, e and o and is sans serif? I've tried Helvetica, Roboto and Noto Sans and none of them worked for those symbols. Or could I be missing something? I tried the following:

- put fonts in ./fonts directory
- add them to mytheme.yml:
```
font:
    catalog:
        NotoSans:
            normal: NotoSans-Regular.ttf
            italic: NotoSans-Italic.ttf
            bold: NotoSans-Bold.ttf
            bold_italic: NotoSans-BoldItalic.ttf
```
- set the font in myfont.yml:
```
base:
    font-family: NotoSans
    font-size: 12
```
- compile the document:
`asciidoctor-pdf -a pdf-theme=mytheme.yml -a pdf-fontsdir=./fonts mydocument.adoc`
