### ISSUE TITLE
sometimes callout number and text go on different pages

### ISSUE THREAD

**Issue by barspi** [asciidoctor/asciidoctor-pdf#1967]
Occasionally, I get the callout number very near the end of the page, and the accompanying text goes on the next page.
I'm attaching a sample screen capture.

<img width="1108" alt="Screen Shot 2021-09-13 at 18 19 09" src="https://user-images.githubusercontent.com/1316018/133158598-d1bcb34b-fa27-4624-a878-c98f4a50dc05.png">

**Comment by barspi** [comment]
Let me add that I'm not doing anything special  in the source:

```asciidoc
<9> The `CardHolder` that owns this `Card`.
It will be _null_ for anonymous cards, such as gift cards.

<10> The `CardProduct` to which this `Card` belongs.

<11> There are various ways in which we associate an account for a `Card` for each incoming transaction.
The system will discover, on the fly, the effective account on which to operate.
```

Also, in my theme I have this defined

```yaml
font:
  catalog:
    M+ 1mn:
      normal: mplus1mn-regular-ascii-conums.ttf
      bold: mplus1mn-bold-ascii.ttf
      italic: mplus1mn-italic-ascii.ttf
      bold_italic: mplus1mn-bold_italic-ascii.ttf

[...]

conum:
  font_family: M+ 1mn
  font_color: $colors_blueicons
  font_size: $base_font_size_min
  line_height: 1.85
  glyphs: circled
```
