### ISSUE TITLE
Theming only partially works for an Example block spanning multiple pages

### ISSUE THREAD

**Issue by tmichett** [asciidoctor/asciidoctor-pdf#1981]
When attempting to provide styles on the **example** portion of the document, the theming doesn't render correctly for the PDFs when the example flows across multiple pages. It actually runs the example theming through the bottom page margins and then stops.

Code (source) boxes on the other hand do exactly what is expected and it allows the code box to honor margins and be split across the pages.

```
code:
  font_color: $base_font_color
  font_family: $literal_font_family
  font_size: ceil($base_font_size * 0.7)
  #font_size: ceil($base_font_size)
  padding: $code_font_size
  line_height: 1.25
  background_color: f5f5f5
  border_color: cccccc
  border_radius: $base_border_radius
  border_width: 0.75

example:
  border_color: #ff8000
  border_radius: $base_border_radius
  border_width: 0.75
  background_color: #ffffc2
  # FIXME reenable margin bottom once margin collapsing is implemented
  padding: $code_font_siz
```

![Example-not-spanning-kills-margin](https://user-images.githubusercontent.com/12944787/139515554-614b3220-6413-4328-a10b-a65cc8fee923.png)
e

**Comment by mojavelinux** [comment]
Please indicate which version of Asciidoctor PDF you are using.

**Comment by ebousse** [comment]
Rather similar problem here with asciidoctor-pdf 1.6.2.

I have the following bit in my theme:
```yaml
example:
  background-color: fcf5c6
```

I compile with `-a media=prepress` and `-d book`, which means odd and even pages are treated differently.

Here is an example of output:
![asciidoctorpb](https://user-images.githubusercontent.com/5868014/154955373-38189489-25dd-47f4-ba60-ef6a38c02077.png)

We can see that the example block that should be spanning from page 10 to the top of page 11 is not correct: the yellow background that should be painted at the top of page 11 is instead drawn at the top of page 12. Essentially, the example block is drawn as if page 12 was following page 10, while it's not.

**Comment by ebousse** [comment]
Strangely I made my problem disappear by changing the font of my examples:

```yaml

font:
  catalog:
    merge: true
    Roboto:
      normal: roboto-normal.ttf
      italic: roboto-italic.ttf
      bold: roboto-bold.ttf
      bold_italic: roboto-bold_italic.ttf

example:
  font-family: Roboto
  background-color: fcf5c6
```

with `Roboto` installed as explain in the docs.

But it's probably just a coincidence…
