### ISSUE TITLE
page-numbering-start-at: cover does not work

### ISSUE THREAD

**Issue by hacker-DOM** [asciidoctor/asciidoctor-pdf#1985]
I have the following files. When I run the following build command, I get a two-page pdf. On the second page, the margins are not 3in.

`main.adoc`:

```adoc
:pdf-theme: pdf-theme.yml

image::minted.pdf[]

Hi!
```

`pdf-theme.yml`:

```yml
extends: default
page:
  layout: portrait
  margin: 3in
  size: A4
```

[minted.pdf](http://mirrors.ctan.org/macros/latex/contrib/minted/minted.pdf)

```bash
$ asciidoctor-pdf --version
Asciidoctor PDF 1.6.0 using Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

I'm getting the same behavior with other pdf files as well.

**Comment by hacker-DOM** [comment]
This is a problem, because we'd like to use a custom title page :)

**Comment by hacker-DOM** [comment]
Just discovered the `:front-cover-image:` attribute. It works, but unfortunately not with page numbering. Here is my new document:

`main.adoc`:
```adoc
:pdf-theme: pdf-theme.yml
:front-cover-image: image::minted.pdf[]

Hi!
```

```
extends: default
page:
  layout: portrait
  margin: 3in
  size: A4
  numbering:
    start-at: cover
```

I would expect the second page to have page number 2, but it has 1.
