### ISSUE TITLE
Current author in footer?

### ISSUE THREAD

**Issue by Alwinator** [asciidoctor/asciidoctor-pdf#1997]
I am currently writing my thesis in asciidoctor. We are a team of four and one requirement is, to add the author of the current part into the footer of the document.

I tried something like the example below, but unfortunately, it didn't work. What is the right approach to achieve my requirement?

```asciidoctor
:current-author: {author_1}
== Topic 1

:current-author: {author_2}
== Topic 2
```

```yaml
footer:
  recto:
    left:
      content: '{current-author}'
```
