### ISSUE TITLE
Set margins for different blocks

### ISSUE THREAD

**Issue by edward-encoord** [asciidoctor/asciidoctor-pdf#2011]
Thanks for this nice tool. I'm wondering if it's possible to set margins for different blocks.

I have tried:

```yml
block:
  margin-top: 0
  margin-bottom: 0
  example:
    margin-top: 10
    margin-bottom: 10
```

and

```yml
block:
  margin-top: 0
  margin-bottom: 0
example:
    margin-top: 10
    margin-bottom: 10
```

but they do not work. Maybe I did something wrong.

__Why I need this.__ For some reason, I need to set both margins of the image block as 0, but I don't want this setting for any other block.

__My current way to set margins for different blocks.__ Now, for the sidebar block and the admonition block, I can set:

```
sidebar:
  border-color: FFFFFF  # white
  border-width: 3
  border-radius: 3
```

so that there is some space because of the thick white border.

For other blocks, I add `ifdef::backend-pdf[{empty} +]` or `ifdef::backend-pdf[---]` between them, and set:

```yml
thematic-break:
  border-color: FFFFFF
  border-width: 0
  margin-top: 1
  margin-bottom: 3
```

Another way is to put all the blocks inside the example block and:

```yml
example:
  padding: [8, 15, 8, 15]
  border-color: FFFFFF  # white
```

So the space between blocks is controlled by `padding`.

---

I'm using `asciidoctor/docker-asciidoctor`:

```
bash-5.1# asciidoctor-pdf -v
Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
