### ISSUE TITLE
Allow line height to be controlled by theme font

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2032]
The line-height property should be accepted for any block that supports font properties defined in the theme. Not only does this allow the line height to be set for the built-in lead role, it also allows the line height to be controlled more consistently throughout the theme.

For example:

```yaml
role:
  lead:
    line-height: 1.3
```

and

```yaml
table:
  head:
    line-height: 1.5
```

Support for this setting should be managed by the `theme_font` helper.
