### ISSUE TITLE
Border color for element should fall back to value of base-border-color

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2134]
If a border color (or column rule color) is not specified for an element, the value should fall back to base-border-color. This allows the border to be toggled solely through the width attribute. For example:

```yml
base:
  border-color: BBBBBB
heading:
  h2:
    border-width: [0, 0, 2, 0]
```

Although this won't impact the built-in themes, the behavior can make creating new themes easier.
