### ISSUE TITLE
First line of abstract does not support normal_italic font style

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2138]
The font style `normal_italic` is not recognized when set on the first line of the abstract in the theme. This style is important as it allows the first line to not inherit the bold style applied to the abstract.

```yml
abstract:
  font-style: bold
  first-line-font-style: normal_italic
```
