### ISSUE TITLE
text-tranform on custom role does not apply to value of attribute reference

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2263]
If a custom role specifies the text-transform key, that transform is not applied to parts of the phrase that are populated by an attribute reference. This happens since the transform is applied before attribute references are resolved.

Example theme:

```yaml
extends: default
role:
  upper:
    text-transform: uppercase
```

Sample document:

```asciidoc
:phrase: uppercase me

[.upper]#{phrase}#
```

The result is `uppercase me` instead of `UPPERCASE ME`.
