### ISSUE TITLE
Text block with background color for safety instructions

### ISSUE THREAD

**Issue by joschober** [asciidoctor/asciidoctor-pdf#2305]
Hi,
according to ANSI / ISO / DIN standard its necessary to style safety instructions with an icon / picture, the signal word and a background color like this:

[picture 1](https://www.doku-abteilung.de/wp-content/uploads/2019/10/image.png)
[picture 2](https://gft-akademie.de/wp-content/uploads/2021/10/Warnhinweise-ANSI-Vorlage.jpg)
[documentation](http://cdn.norgren.com/pdf/M_P75661_E_148000_DE_EN.pdf)

That's not really possible with asciidoc right now, right?  I tried with a custom role, but it doesn't look very nice.

![customrole](https://user-images.githubusercontent.com/106801403/183671160-a0ba0bd2-57dd-4f6c-829c-b3395b454aa5.png)

Would it be possible to add a functionality for background colors at text blocks or headlines for the whole width? Or an extension of the admonitions?

**Comment by mojavelinux** [comment]
There's an example in the docs that shows how to do this using an extended converter.

https://docs.asciidoctor.org/pdf-converter/latest/extend/use-cases/#theme-admonition-per-type

Here's the custom theme you would use with that extended converter:

```yaml
extends: default
admonition:
  important:
    column-rule-width: 0
    background-color: #E51B20
    font-color: #FFFFFF
    padding: [12, 6]
  icon:
    important:
      name: fas-exclamation-triangle
      stroke-color: #FFFFFF
```

In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org.
