### ISSUE TITLE
Use em units for big and small roles

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2307]
The font size for the big and small roles should be expressed in em units (relative) rather than pt (fixed). This will allow them to scale relative to the current font size of the text to which they are applied.

```
role:
  big:
    font-size: 1.25em
  small:
    font-size: 0.8em
```

This differs slightly from HTML, which uses calc(12em / 10) for big and calc(10em / 12) for small. But it's easier to manage values that don't have a repeating decimal.
