### ISSUE TITLE
Allow font settings to be set per side for running content periphery

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2316]
Currently, the font settings can be specified per periphery (e.g., footer-font-color) or per position (e.g., footer-recto-right-font-color). The theme should also permit specifying the font settings per side of a periphery (e.g., footer-recto-font-color).

```
footer:
  recto:
    font-color: AA0000
    ...
```
