### ISSUE TITLE
How to turn off PDF running header and footer for title and other pages

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#232]
I would suggest logically something like:
- title_page_header: off | on ; default = off
- title_page_footer: off | on ; default = off
- preamble_header: off | on ; default = off
- preamble_footer: off | on ; default = off
- preamble_header: off | on ; default = off
- preamble_footer: off | on ; default = off

I did try the Header section attribute :no-header-footer: but this made no difference.

**Comment by mojavelinux** [comment]
Are you referring to the running header and footer? That should be disabled automatically on the title and toc page. We don't yet have controls for other pages. We need to think about how best to express that without making the configuration overly verbose.

**Comment by mojavelinux** [comment]
I think better would be a `locations` value in the theme that controls this. Something like:

```
header:
  locations: preamble,content
```

(That would also be the default). However, before we do this, we need to determine all the named page types in the PDF document. This terminology has not yet been established in the AsciiDoc ecosystem, so we don't have anything to build on. Probably best to build on naming that has been worked out in other toolchains (like DocBook, DITA, etc).

**Comment by wolandscat** [comment]
Yep, that's a nicer idea. Coming from the document publishing world pre-DITA, I would say there are no standard document parts. In FrameMaker, each chunk of content is normally in its own file, which is where you set running headers and footers.

Another approach, just to think about: assuming that a large doc in asciidoc is just one file (to make life easier - multiple files starts to be a pain with no UI tool) what if 'header' and 'footer' macros could repeatedly be used all through the file, in the same way that :numbered:  / :numbered!: can? In fact the recto/verso content specifications currently in the PDF style .yml file could go there instead, i.e. the equivalent of the following in some sort of macro:

```
header:
  recto_content:
    left: image:images/openehr-logo-150x50.png[]
    right: '{section-or-chapter-title}'
  verso_content:
    left: '{section-or-chapter-title}'
    right: image:images/openehr-logo-150x50.png[]
footer:
  recto_content:
    center: '*Page {page-number}* | {page-count}'
  verso_content:
    center: '*Page {page-number}* | {page-count}'
```
