### ISSUE TITLE
Headers not printed if marked as index terms

### ISSUE THREAD

**Issue by realharry** [asciidoctor/asciidoctor-pdf#2324]
Anything that is included inside the index terms `((...))` in the headers `====` and below (e.g., `=====`) are not included in the final output.

Example:

```
=== ((Everything)) is fine 
==== The ((Weird)) Thing
===== ((Ghost))
Apple
```

Will generate the following output (for example)

```
3.2 Everything is fine
3.2.1 The Thing

Apple
```

**Comment by realharry** [comment]
This particular example is taken from `:doctype: book` and section number down to 3 (this must be a default?)

**Comment by mojavelinux** [comment]
I'm unable to reproduce the behavior you are reporting using Asciidoctor PDF 2.3. Here's the example I used:

```
= Document Title
:doctype: book

== The ((Weird)) Thing

=== The ((Weirder)) Thing

==== The ((Weirdest)) Thing

===== ((Ghost))

[index]
== Index        
```

Please provide a reproducible example if you can prove otherwise.

**Comment by realharry** [comment]
(d*ng, I accidentally pressed the back button, and what I wrote is all gone. :) (Seriously, github! ;))

Anyways, trying again. 

(1) @mojavelinux thanks. long story short. ;) I can consistently repro this on my setup, but it's very likely due to my particular settings (or, the interactions between the settings). Here's the generated output pdf file. Note the TOC chapter 3, and the content in chapter 3. (this is created for illustration purposes only.)

Chapter 3 looks like this:

```
== ((Program Initialization and Execution))
=== ((Program)) Execution
```
 
[golang-mini-reference-20220814.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/9438090/golang-mini-reference-20220814.pdf)

**Comment by realharry** [comment]
(2) They don't let me attach adoc file and yml files for some reason...


To part of the top level adoc

```
= Golang Mini Reference 2022: A Quick Guide to the Modern Go Programming Language for Busy Coders
Harry Yoon v1.0, {localdate}
:doctype: book
:docinfo:
:title-page:
ifdef::backend-pdf[]
:toc: macro
endif::[]
ifndef::backend-pdf[]
:toc:
endif::[]
:toclevels: 2
:sectnums:
:partnums:
:pagenums:
// :chapter-label: Lesson
:chapter-label: 
:source-highlighter: pygments
:pygments-style: vs
:pygments-linenums-mode: inline
:icons: font
```

paperback-theme.yml
```
extends: default
base:
  font_color: #000000
title-page:
  # logo:
  #   image: image:book/cover.png[]
  #   top: 50%
  title:
    top: 25%
page:
  size: [7.0in, 10.0in]
  margin: [1.25in, 0.75in, 1.125in, 0.75in]
  # margin: [1.25in, 1.05in, 1.125in, 1.05in]
  margin-inner: 1.25in
  margin-outer: 0.75in
# page-numbering-start-at: 7
heading:
  part:
    break-before: always
  chapter:
    # break-before: auto
    break-before: always
header:
  border_color: DDDDDD
  height: 1.125in
  line-height: -5
  vertical-align: middle
  recto:
    right:
      content: '_{section-title}_'
  verso:
    left:
      content: '_{section-title}_'
footer:
  height: 0.925in
# code:
#   font_size: ceil($base_font_size * 0.85)
code:
  font_family: Fira Code
  font_size: ceil($base_font_size * 0.85)
literal:
  font_family: Fira Code
# heading:
#   h2-font-size: 38
#   h2-align: left
#   h3-font-size: 28
#   h3-align: left
font:
  catalog:
    EBGaramond:
      normal: ebgaramond-normal.ttf
      italic: ebgaramond-italic.ttf
      bold: ebgaramond-bold.ttf
      bold_italic: ebgaramond-bold_italic.ttf
    Adobe Caslon Pro:
      normal: adobe-caslon-pro-regular.ttf
      italic: adobe-caslon-pro-italic.ttf
      bold: adobe-caslon-pro-bold.ttf
      bold_italic: adobe-caslon-pro-bold_italic.ttf
    Libre Caslon Text:
      normal: LibreCaslonText-Regular.ttf
      italic: LibreCaslonText-Italic.ttf
      bold: LibreCaslonText-Bold.ttf
      bold_italic: LibreCaslonText-Italic.ttf
    Noto Serif:
      normal: GEM_FONTS_DIR/notoserif-regular-subset.ttf
      bold: GEM_FONTS_DIR/notoserif-bold-subset.ttf
      italic: GEM_FONTS_DIR/notoserif-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/notoserif-bold_italic-subset.ttf
    Fira Code:
      normal: FiraCode-Regular.ttf
      bold: FiraCode-SemiBold.ttf
      italic: FiraCode-Medium.ttf
      bold_italic: FiraCode-Medium.ttf
    # M+ 1mn supports ASCII and the circled numbers used for conums
    M+ 1mn:
      normal: GEM_FONTS_DIR/mplus1mn-regular-subset.ttf
      bold: GEM_FONTS_DIR/mplus1mn-bold-subset.ttf
      italic: GEM_FONTS_DIR/mplus1mn-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/mplus1mn-bold_italic-subset.ttf
  fallbacks: 
  - M+ 1mn

```

My setup is orignally based on the Git Pro 2 book, and they are more or less the same.
