### ISSUE TITLE
Don't require the pdf-fontsdir attribute in order to use custom fonts

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#2349]
When a theme uses custom fonts, it's mandatory to set the the `pdf-fontsdir` attribute. Otherwise, the converter will not be able to locate the font files. This requirement makes it slightly more difficult to create a custom theme. The converter should instead provide a reasonable fallback if this attribute is not set.

There are several ways which this could be done.

First, the theme could expand the token `THEMES_DIR` at the beginning of the font path in the theme, much like it does for the `GEM_FONTS_DIR` token. The `THEMES_DIR` token would resolve to the value of the `pdf-themesdir` attribute (which defaults to the directory of the main theme file that was loaded).

```yml
font:
  catalog:
    Lato: THEMES_DIR/Lato-Regular.ttf
```

Second, the default `pdf-fontsdir` could be changed from `GEM_FONTS_DIR` to `{pdf-themesdir};GEM_FONTS_DIR`, where `{pdf-themesdir}` represents the value of the `pdf-themesdir` attribute. When this default is used, relative font paths in the theme are resolved from the themes dir (the directory of the theme file) first before being resolved from the installed gem. The user will still be able to override this default by setting the `pdf-fontsdir` attribute. And this won't affect built-in themes, which use the `GEM_FONTS_DIR` token explicitly to refer to paths inside the gem.

For completeness, we could also consider allowing the attribute reference `{pdf-themesdir}` to be used in the value of `pdf-fontsdir` when set from the CLI or API (e.g., `-a pdf-fontsdir={pdf-themesdir}/fonts`). Though that's not really addressing the original issue.

**Comment by mojavelinux** [comment]
I'm also thinking that the `pdf-fontsdir` should expand to the current directory if the value is empty. Right now, this value is interpreted as GEM_FONTS_DIR. However, that's not very logical.

**Comment by life888888** [comment]
Under the Asciidoctor PDF 2.3.0 current rules, I have tested several usage methods, all of which can be executed

1. Provide self-made fonts and themes using the directory method
2. Use jar to provide self-made fonts and themes
3. Use the directory method to provide self-made fonts and themes with custome theme
4. Use jar to provide custom fonts and themes with custome theme

But I haven't tested

5. Use the directory method to provide self-made fonts and themes with custome theme + custome font
6. Use jar to provide self-made fonts and themes with custome theme + custome font


directory method

```bash 
~/downloaded-resources
├── fonts
│   ├── notosans-cjk-tc-bold_italic.ttf
│   ├── notosans-cjk-tc-bold.ttf
│   ├── notosans-cjk-tc-italic.ttf
│   └── notosans-cjk-tc-normal.ttf
└── themes
    └── default-ext-notosans-cjk-tc-theme.yml
```

jar method  ~/libs/pdf-ext-notoserif-cjk-tc.jar

``` bash
pdf-ext-notoserif-cjk-tc.jar
└── data
    ├── fonts
    │   ├── notoserif-cjk-tc-bold_italic.ttf
    │   ├── notoserif-cjk-tc-bold.ttf
    │   ├── notoserif-cjk-tc-italic.ttf
    │   └── notoserif-cjk-tc-normal.ttf
    └── themes
        └── default-ext-notoserif-cjk-tc-theme.yml
```

custom theme

```bash
src/docs/asciidoc
├── custom-theme
│   └── custom-default-ext-notosansmono-cjk-tc-theme.yml
└── README-zh_TW.adoc
```

Inheritance tree of my theme

```bash
default (System)
└── default-ext-notosansmono-cjk-tc (My Direcroty or Jar)
     └─ custom-default-ext-notosansmono-cjk-tc (In adoc file sub dir)
```

1 [cjk-use-file-example](https://github.com/life888888/asciidoctor-pdf-cjk-ext-gradle-examples/tree/main/cjk-use-file-example)

```gradle
        "pdf-fontsdir": "${System.getProperty("user.home")}/downloaded-resources/fonts;GEM_FONTS_DIR;",
        "pdf-themesdir": "${System.getProperty("user.home")}/downloaded-resources/themes",
        "pdf-theme": "default-ext-notosans-cjk-tc"
```

2 [cjk-use-jar-example](https://github.com/life888888/asciidoctor-pdf-cjk-ext-gradle-examples/tree/main/cjk-use-jar-example)

```gradle
        "pdf-fontsdir": "uri:classloader:/data/fonts;GEM_FONTS_DIR;",
        "pdf-themesdir": "uri:classloader:/data/themes",
        "pdf-theme": "default-ext-notoserif-cjk-tc"
```

3 [cjk-with-theme-use-file-example](https://github.com/life888888/asciidoctor-pdf-cjk-ext-gradle-examples/tree/main/cjk-with-theme-use-file-example)

```gradle
        "pdf-fontsdir": "${System.getProperty("user.home")}/downloaded-resources/fonts;GEM_FONTS_DIR;",
        "pdf-themesdir": "${System.getProperty("user.home")}/downloaded-resources/themes",
        "pdf-theme": "${sourceDir}/custom-theme/custom-default-ext-notosans-cjk-tc-theme.yml"
```
4 [cjk-with-theme-use-jar-example](https://github.com/life888888/asciidoctor-pdf-cjk-ext-gradle-examples/tree/main/cjk-with-theme-use-jar-example)

```gradle
        "pdf-fontsdir": "uri:classloader:/data/fonts;GEM_FONTS_DIR;",
        "pdf-themesdir": "uri:classloader:/data/themes",
        "pdf-theme": "${sourceDir}/custom-theme/custom-default-ext-notosansmono-cjk-tc-theme.yml"
```

**Use custom theme , I must tell pdf-theme full path file name, not short theme name.**

        **"pdf-theme": "${sourceDir}/custom-theme/custom-default-ext-notosansmono-cjk-tc-theme.yml"**



My `default-ext-notosans-cjk-tc-theme.yml`

```yml
extends: default-with-font-fallbacks
font:
  catalog:
    merge: true
    Noto Sans CJK TC:
      normal: notosans-cjk-tc-normal.ttf
      bold: notosans-cjk-tc-bold.ttf
      italic: notosans-cjk-tc-italic.ttf
      bold_italic: notosans-cjk-tc-bold_italic.ttf
  fallbacks: [M+ 1p Fallback, Noto Emoji, Noto Sans CJK TC]      
base_font_family: Noto Sans CJK TC
```

My `custom-default-ext-notosansmono-cjk-tc-theme.yml`

```yml
extends:
  - default-ext-notosansmono-cjk-tc
title-page:
  align: left
  logo:
    image: image:{docdir}/custom-theme/cover.png[align=center]
   # image: image:{docdir}/images/cover.png[align=center]    
    top: 0%
page:
  margin: [0.75in, 1in, 0.75in, 1in]
base:
  line-height-length: 20
heading:
  font-color: #FF8000
  font-size: 12
  line-height: 1.2
link:
  font-color: #009900
header:
  height: 0.75in
  line-height: 1
  recto:
    right:
      content: '{document-title}'
  verso:
    left:
      content: '{document-title}'
footer:
  height: 0.75in
  line-height: 1
  recto:
    right:
      content: '{chapter-title} | *{page-number}*'
  verso:
    left:
      content: '*{page-number}* | {chapter-title}'
image:
  align: center
caption:
  align: center
  font-color: #FF0000
  font-size: 10
```

But the above are all setting parameters that have been tested and can be passed.

I don't tested

5. Use the directory method to provide self-made fonts and themes with custome theme + custome font
6. Use jar to provide self-made fonts and themes with custome theme + custome font

Restriction: The way of using jar cannot be used for Asciidoctor and Asciidoctor PDF, but it can be used for AsciidoctorJ and Asciidoctor Gradle Plugin , Asciidoctor Maven Plugin.
