### ISSUE TITLE
code won't form with the theme

### ISSUE THREAD

**Issue by keliansrdl** [asciidoctor/asciidoctor-pdf#2353]
Hello, my code sections do not take the theme

asciidoctor-pdf version :
![image](https://user-images.githubusercontent.com/100124349/195293815-bda6d85a-360a-43d6-a05c-266c48ca8e98.png)

part of the theme "code" block in theme.yml : 
``` 
code:
  font-color: #333333
  font-family: Courier Prime Sans
  font-style: normal
  font-size: 10
  background-color: #f6f6f6
  border-color: #0f80aa
  border-radius: 2
```

code in my .adoc file

```
[source,powershell]
----
Get-Command New*
----
```

command :

```
asciidoctor-pdf -a pdf-themesdir=. -a pdf-theme=theme.yml -a pdf-fontsdir=fonts -a iconsdir=icons myfile.adoc
```

result : 
![image](https://user-images.githubusercontent.com/100124349/195294783-dc5a292c-9107-463e-ace3-92674e828bc4.png)

Do you have any idea pls ?
