### ISSUE TITLE
Same image path setting but have different result path.

### ISSUE THREAD

**Issue by life888888** [asciidoctor/asciidoctor-pdf#2361]
Asciidcotor PDF version 2.3.2
``` bash
$ asciidoctor-pdf -v
Asciidoctor PDF 2.3.2 using Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

My Project Path and  File Tree

```bash
/home/demo/Documents/LAB1
├── images
│   └── example_page.png
├── README.adoc
└── resources
    └── themes
        ├── basic-theme.yml
        └── logo.png
``` 

README,adoc header

```adoc
:pdf-themesdir: resources/themes
:pdf-theme: basic
```

basic-theme.yml

```yml
extends: default
title-page:
  align: left
  logo:
    image: image:{docdir}/resources/themes/logo.png[align=center]
    top: 0%
image:
  align: center
caption:
  align: center
page:
  layout: portrait
  margin: [2.5cm, 2.5cm, 2cm, 2.5cm]
heading:
  font-color: #2f5496
  h1-margin-page-top: 5cm
  h1-margin-bottom: 5cm
  # h1 is used for part titles (book doctype) or the doctitle (article doctype)
  h1_font_size: floor($base_font_size * 2.6)
  # h2 is used for chapter titles (book doctype only)
  h2_font_size: floor($base_font_size * 1.5)
  h3_font_size: floor($base_font_size * 1.25)
  h4_font_size: $base_font_size_large
  h5_font_size: $base_font_size
  h6_font_size: $base_font_size_small
header:
  height: 2.5cm
  recto:
    right:
      # OK
      content: 'image::./logo.png[width="200"]'
      # FAIL
      # content: image:{docdir}/resources/themes/logo.png[align=center]
  verso:
    left:
      content: $header-recto-right-content      
```

Please note this setting: `image:{docdir}/resources/themes/logo.png[]`

title-page_logo_image:  image:{docdir}/resources/themes/logo.png[align=center] IS OK

![title-page-logo-image](https://user-images.githubusercontent.com/101442875/197759393-3edd97f6-a8bf-48e4-af19-734ee67b4fb0.png)

But  `header_recto_right_content:  image:{docdir}/resources/themes/logo.png[align=center]` IS FAIL

![header_recto_right_content](https://user-images.githubusercontent.com/101442875/197759697-52a5431d-e9c3-497c-8225-d59274934aa2.png)

```bash
$ asciidoctor-pdf -a doctype=book README.adoc
asciidoctor: WARNING: image to embed not found or not readable: /home/demo/Documents/LAB1/resources/themes/home/demo/Documents/LAB1/resources/themes/logo.png
...
```

 `header_recto_right_content:  image:{docdir}/resources/themes/logo.png[align=center]`  Read Wrong Path `/home/demo/Documents/LAB1/resources/themes/home/demo/Documents/LAB1/resources/themes/logo.png`

BUT `header_recto_right_content:  image:{docdir}/resources/themes/logo.png[align=center]` Read Correct Path 
`/home/demo/Documents/LAB1/resources/themes/logo.png`

Same Image Path setting ` image:{docdir}/resources/themes/logo.png[]`

`title-page_logo_image` and `header_recto_right_content` have different image path result !

Same image path setting but have different result path.
