### ISSUE TITLE
Support more granular display for title-page-revision

### ISSUE THREAD

**Issue by ryandcarter** [asciidoctor/asciidoctor-pdf#2362]
For theming PDF front covers, the title-page-revision (https://docs.asciidoctor.org/pdf-converter/latest/theme/title-page/#revision) only has the display:none option. So revdate:revnumber.. or nothing at all. My particular use-case is to only display the revdate , and none of the other info.

It would be nice if you could tailor it similar to that of title-page-authors(https://docs.asciidoctor.org/pdf-converter/latest/theme/title-page/#authors):

```
title-page:
  revision:
    content:
      revdate_only: "{revdate}"
      ....
```
