### ISSUE TITLE
Bibliography styling

### ISSUE THREAD

**Issue by cristian-5** [asciidoctor/asciidoctor-pdf#2407]
We should have a selector in the `theme.yml` that allows us to change the appearance of the bibliography item list, something like this:

``` yml
bibliography:
  item-spacing: 6
  font-color: #000000
  style: circle
  link-color: #FF0000
```

Note the `style` property allowing us to chose from different list styles, with the addition of `none` to hide the bullet point.
Also note the `link-color` that only applies to external links in the bibliography.
