### ISSUE TITLE
Font style(bold, italic, bold_italic) does not apply to table titles and headers when using fullback fonts

### ISSUE THREAD

**Issue by jay-liao86** [asciidoctor/asciidoctor-pdf#2423]
I'm a user of this repo from China who needs to use English and Chinese in single documents.
My theme file is as below:
```yml
extends: default-sans
font:
  catalog:
    merge: true
    Noto Sans CN:
      normal: NotoSansSCRegular.ttf
      bold: NotoSansSCBold.ttf
      italic: 江城斜黑体 400W.ttf
      bold_italic: 江城斜黑体 700W.ttf
  fallbacks:
    - Noto Sans CN
    - Noto Emoji
```
My adoc file is as below:
```adoc
*粗体中文(Bold Chinese)*

_斜体中文(Italic Chinese)_

*_粗斜体中文(Bold Italic Chinese)_*

.A table with a title 中文
|===
|Column 1, header row 中文

|Cell in column 1, row 2 中文
|===
```
The output is like this:
![WX20230522-145011@2x](https://github.com/asciidoctor/asciidoctor-pdf/assets/4397864/a3ab83fd-6ff3-47f1-b822-753ee86fa744)
