### ISSUE TITLE
listing block font-size is a fixed value?

### ISSUE THREAD

**Issue by Baerbeisser** [asciidoctor/asciidoctor-pdf#2499]
I've set `base_font_size: 10` but the listing blocks look like this:

![Bildschirmfoto_2024-02-22_21-50-02](https://github.com/asciidoctor/asciidoctor-pdf/assets/22264628/e327ebf6-c889-40f4-a0f0-23fdc78b1e68)

I find [here](https://docs.asciidoctor.org/pdf-converter/latest/theme/block/) that `block:` only has margin keys, but listing block counts as `code:`, but `font-size` works neither there.

edit: `code: font-size` doesn't work at all for listing block in my example? And changing `code:` to `base:` adds to base_font_size, making everything size 2 or so, *except* the listing block.

`base:     font-color: #FF0000` works, everything gets red.

What i want is, to have listing block font-size about as small as the rest of  the text.

Here is my theme.yml:
```
extends:
- default
- default-with-font-fallbacks
font:
  catalog:
    merge: true
    Roboto:
      normal: /usr/share/fonts/TTF/Roboto-Regular.ttf
      italic: /usr/share/fonts/TTF/Roboto-Italic.ttf
      bold: /usr/share/fonts/TTF/Roboto-Bold.ttf
      bold_italic: /usr/share/fonts/TTF/Roboto-BoldItalic.ttf
base_font_family: Roboto
fallbacks: [Roboto]
base_font_size: 10
heading_h1_font_size: 19
heading_h2_font_size: 16
heading_h3_font_size: 14
heading_h4_font_size: 12
heading_h5_font_size: 10
heading_h6_font_size: 8
code:
    font-size: 10
```
