### ISSUE TITLE
Opening PDF with evince provides following error: Syntax Error (216187): Too few (0) args to 'Tr' operator

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#251]
Any idea what Syntax Error (216187): Too few (0) args to 'Tr' operator is about? The PDF looks fine, just when I open with evince I see these errors on the shell.

**Comment by rlopez133** [comment]
Ok this is weird, when I open the PDF via firefox, I can see the footer information just fine, i.e. page numbers. When I open with evince it is missing.

Output of firefox:
![selection_241](https://cloud.githubusercontent.com/assets/8877333/8415142/6aadb6c4-1e62-11e5-97bb-83656650e1c7.png)

Output of evince and adobe:
![selection_242](https://cloud.githubusercontent.com/assets/8877333/8415160/813c43ba-1e62-11e5-8416-58176e81eaaa.png)

**Comment by mojavelinux** [comment]
Looks like some sort of error in how the footer data is added, perhaps due to an overrun.

**Comment by rlopez133** [comment]
My older asciidoctor-pdf dev env which I'm keeping as my control for now does not have the issue FYI.

**Comment by mojavelinux** [comment]
I found the culprit here. This traces back to the problem with the pdf import, which is used to add the back cover page. There's another function that was removed from Prawn that we need in order to make this work. As a result, it's messing with the running content. I'll apply a fix and test it.

**Comment by mojavelinux** [comment]
Btw, here's a clear way to define your footer content:

```
footer:
  font_size: $base_font_size_small
  font_color: $base_font_color
  font_style: bold
  border_color: dddddd
  border_width: 0.25
  height: $base_line_height_length * 2.5
  padding: [$base_line_height_length / 2, 1, 0, 1]
  valign: top
  recto_content:
    left: 'www.redhat.com'
    center: '{page-number}'
    right: '\refarch-feedback@redhat.com'
  verso_content:
    left: $footer_recto_content_right
    center: $footer_recto_content_center
    right: $footer_recto_content_left
```

Notice that I used the `font_style` to set bold instead of having to format each entry in the content. I also used variable names to swap the content on alternating pages so the content only has to be entered (and maintained) in one pace. The intent is also clearer.

You do have to escape the e-mail entry using a backslash if you don't want it to appear as a link.
