### ISSUE TITLE
prose_margin_inner has no effect on prose in table cells

### ISSUE THREAD

**Issue by Mutantpenguin** [asciidoctor/asciidoctor-pdf#2518]
prose_margin_inner should work inside table cells, or table cells should support setting their own inner margin for prose.

## Example doc:
```asciidoc
= Title LVL 1
:doctype: book
:data-uri: {docdir}
:pdf-theme: theme.yml

== Title LVL 2

This is a text.

This is another text.

[%unbreakable%header,cols="1,2"]
|===

|Col 1
|Col 2

|a small text with one line
|
This is a text.

This is another text.

|===
```

## Example theme:
```yaml
extends: default-sans-with-font-fallbacks
prose:
  margin:
    inner: 60
```

## Screenshot
![image](https://github.com/asciidoctor/asciidoctor-pdf/assets/9027507/7fd7da6c-af75-4d61-b45c-f328f20cd208)
