### ISSUE TITLE
line break in theme attribute "with_email" not working any more

### ISSUE THREAD

**Issue by pykereaper** [asciidoctor/asciidoctor-pdf#2519]
I'm in the progress of upgrading from `org.asciidoctor.jvm.pdf` 3.3.2 to 4.0.2.  
All in all, the progress went relatively smoothly with only minor changes to make. However, there's one thing I'm missing.

I'm using this setting in my custom theme:

```yaml
title-page:
  authors:
    content:
      with_email: "{author}\n{email}"
```

Notice the `\n` to make a line break. This worked flawlessly in 3.3.2. In 4.0.2 this one produces only a space character, but not a newline. Inserting unicode chars doesn't work either.

Is it still possible in 4.0.2 to define a line break?

**Comment by mojavelinux** [comment]
The correct syntax is as follows:

```yml
extends: default
title-page:
  authors:
    content:
      with_email: |
        {author} +
        {email}
```

or

```
extends: default
title-page:
  authors:
    content:
      with_email: "{author} +\n{email}"
```

The value supports inline AsciiDoc and to make a hardbreak in a line of AsciiDoc, it requires ` +\n`. This change was introduced in Asciidoctor PDF 2 by #1642.

If you need additional support, please direct your questions to the project chat at https://chat.asciidoctor.org.
