### ISSUE TITLE
Unicode icons/emojis missing in bundled fallback font

### ISSUE THREAD

**Issue by thomas-ferchau** [asciidoctor/asciidoctor-pdf#2555]
The bundled fallback font `data/fonts/notoemoji-subset.ttf` seems to lack many Unicode icons/emojis. It is possible to work around that, but maybe it can be improved to avoid frustration.

Example log output:
`asciidoctor: WARNING: Could not locate the character `❌' (\u274c) in the following fonts: Noto Sans, M+ 1p Fallback, Noto Emoji`

More examples of icons/emojis that I used:
```
`➕' (\u2795)
`➖' (\u2796)
`❓' (\u2753)
`❌' (\u274c)
`🟢' (\u1f7e2)
```

**Possible Solution**

It should be possible to extend the bundled font file. My suggestions:

1. Download a new version of the font.
   It has recently been updated to Unicode 16.0 (Oct 3, 2024, see [releases](https://github.com/googlefonts/noto-emoji/releases)) while the revision currently listed in [data/fonts/ABOUT-notoemoji-subset](https://github.com/asciidoctor/asciidoctor-pdf/blob/main/data/fonts/ABOUT-notoemoji-subset) ([16151a2312a1f8a7d79e91789d3cfe24559d61f7](https://github.com/googlefonts/noto-emoji/commit/16151a2312a1f8a7d79e91789d3cfe24559d61f7) from Oct 17, 2019) was created even before Unicode 12 ([released](https://github.com/googlefonts/noto-emoji/releases/tag/v2019-11-19-unicode12) after that commit).

2. Maybe less glyphs have to be removed? [data/fonts/ABOUT-notoemoji-subset](https://github.com/asciidoctor/asciidoctor-pdf/blob/main/data/fonts/ABOUT-notoemoji-subset) states:
   `Some glyphs have been removed that conflict with the other built-in fonts to produce the notoemoji-subset.ttf font.`

**Workaround**

My workaround is to download the latest [Noto Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji) font, put `NotoEmoji-Regular.ttf` in a directory and configure that font as fallback in the PDF theme. I did not see any problems with glyphs that conflict with the other built-in fonts and should be removed from the font, but I also do not know which ones to look for.

`pdf-theme.yml`
```yaml
extends: default-sans-with-font-fallbacks
font:
  catalog:
    merge: true
    # Noto Emoji is an open source font with support for the latest Unicode emoji specification.
    # https://fonts.google.com/noto/specimen/Noto+Emoji
    Noto Emoji Full Set: NotoEmoji-Regular.ttf
  # Configure Fallback Font for more Unicode icons/emojis because the fonts bundled with asciidoctor-pdf miss many:
  # asciidoctor: WARNING: Could not locate the character `❌' (\u274c) in the following fonts: Noto Sans, M+ 1p Fallback, Noto Emoji
  # https://docs.asciidoctor.org/pdf-converter/latest/theme/fallback-font/
  fallbacks: [M+ 1p Fallback, Noto Emoji Full Set]
```

Attributes in the Asciidoctor documents (or in an included global configuration file):
```
:pdf-themesdir: {docdir}/themes
:pdf-fontsdir: {docdir}/fonts
:pdf-theme: pdf-theme.yml
```
