### ISSUE TITLE
quote not styled with yml declaration

### ISSUE THREAD

**Issue by Sulquendi** [asciidoctor/asciidoctor-pdf#2561]
Hello,

Apparently asciidoctor-pdf does not handle `[quote]` and markdown quotes with `>` the same way : 

tried this :

```
[quote]
----
This is a
multi-line
quote
----

> This is a 
> multi-line
> markdown quote
```

With this quote style in theme.yml :
```
quote:
  font-family: Helvetica
  border-color: $branded-color
  padding: [10, 10, 10, 10]
```

And it turns out that only the markdown block quote is styled accordingly
