### ISSUE TITLE
{revnumber} always appears as "1" in PDF header

### ISSUE THREAD

**Issue by michael-taylor** [asciidoctor/asciidoctor-pdf#2567]
Hello,

I'm using the AsciiDoctor docker image to build a PDF and when I have **{revnumber}** in the header of the PDF theme, it always shows "1" in the page headers, even when the version appears correctly on the title.

Here is my document header:

```
= {title redacted}
:revdate: May 6, 2025
:revnumber: 2
:doctype: book
```

Here is my PDF theme:

```
extends: base
base:
  font-size: 10.5
page:
  size: Letter
  margin: [1in, 0.5in, 1in, 0.5in]
image:
  align: center
  caption:
    text-align: center
table:
  align: center
  caption:
    text-align: center
header:
  height: 0.75in
  line-height: 1
  font-size: 8
  recto:
    right:
      content: '{document-title}'
    center:
      content: '{chapter-title}'
    left:
      content: 'Ver {revnumber}'
  verso:
    left:
      content: '{document-title}'
    center:
      content: '{chapter-title}'
    right:
      content: 'Ver {revnumber}'
footer:
  height: 0.75in
  line-height: 1
  columns: =100%
  font-size: 8
  recto:
    center:
      content: '{page-number}'
  verso:
    center:
      content: '{page-number}'
```
