### ISSUE TITLE
Allow content in header/footer to be specified once when the same for recto and verso

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#268]
When the content for the running header/footer is the same on recto and verso pages, allow it to be specified without the granularity of recto and verso.

Example:

``` yaml
footer:
  content:
    left: ...
    right: ...
```

When the `content` key is specified, the `recto_content` and `verso_content` keys should be ignored.

**Comment by mojavelinux** [comment]
Keep in mind that this can be achieve using a YAML reference:

```yml
footer:
  columns: =100%
  recto: &shared-footer
    center:
      content: '{page-number}'
  verso: *shared-footer
```
