### ISSUE TITLE
Add padding on sidebar content in PDF

### ISSUE THREAD

**Issue by mraible** [asciidoctor/asciidoctor-pdf#344]
There is no padding in a sidebar. It'd be nice if it looked more like the HTML5 or EPUB version.

PDF sidebar:
<img width="738" alt="pdf-sidebar" src="https://cloud.githubusercontent.com/assets/17892/10790267/f144975e-7d47-11e5-8b7c-c826685ff823.png">

HTML5 sidebar:
<img width="999" alt="html5-sidebar" src="https://cloud.githubusercontent.com/assets/17892/10790280/ffa70ffc-7d47-11e5-930e-087c07c13c76.png">

**Comment by mojavelinux** [comment]
This is very likely the result of editing the theme. You need to set the following key in your theme file:

```
sidebar:
  padding: [top, right, bottom, left]
```

This information is missing from the theming guide. I'll add it.

**Comment by mraible** [comment]
I copied my theme from the default one and it does have sidebar padding information in it:

```
sidebar:
  border_color: $page_background_color
  border_radius: $base_border_radius
  border_width: $base_border_width
  background_color: eeeeee
  # FIXME reenable margin bottom once margin collapsing is implemented
  padding: [$vertical_rhythm, $vertical_rhythm * 1.25, 0, $vertical_rhythm * 1.25]
  title:
    align: center
```

I tried changing it to be the following. This causes the title to align left, but there's still no padding.

```
  padding: [12, 15, 12, 15] 
  title:
    align: left
```
