### ISSUE TITLE
Background Image in Header

### ISSUE THREAD

**Issue by abradshaw** [asciidoctor/asciidoctor-pdf#356]
Id like to request the ability to place an image in the header of pages. Maybe even a different ones for left/right pages

**Comment by DavidGamba** [comment]
Haven't tried it on the header, but it works on the footer:

```
footer:
   height: 0.5in
   border_color: #000000
   recto: # odd pages
      content:
         left: '{page-number}'
         center: '©2015 {company} v{docversion}, {docdate}'
         right: 'image:common/logo.png[width=150]'
   verso: # even pages
      content:
         left: 'image:common/logo.png[width=150]'
         center: '©2015 {company} v{docversion}, {docdate}'
         right: '{page-number}'
```

Just make sure your `imagesdir` and `base_dir` is set.
