### ISSUE TITLE
header recto/verso content image size

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#359]
Dan,

Trying to modify the size of a png file within my yaml file

````
header:
  height: 0.75in
  image_valign: 10
  recto_content:
    right: image:/home/template_images/rh-logo.png[width=300]
  verso_content:
    left: image:/home/template_images/rh-logo.png[width=300]

````

I've changed the value of width to all sorts of different values but still keep getting the same image size. This worked for me previously not sure why it isn't working now. Before I had a diff image and set the width to 25. Now I'm just playing with the value to see if I can make it bigger but no go.
