### ISSUE TITLE
Allow headings to be aligned

### ISSUE THREAD

**Issue by wsidl** [asciidoctor/asciidoctor-pdf#399]
Would it be possible to add an option for headings? You can align the base style and other block types, but headings don't have the option.

An option would be similar to this:
````yaml
heading:
    h2:
        font_size: 16
        align: center
````
