### ISSUE TITLE
rendering callouts

### ISSUE THREAD

**Issue by gliptak** [asciidoctor/asciidoctor-pdf#409]
Trying to render callout like:

    :doctype: book
    :source-highlighter: pygments
    
    [source,ruby]
    ----
    print 'hello' # <1>
    ----
    <1> first callout

Rendering with built-in fonts I see:

   The following text could not be fully converted to the Windows-1252 character set:
   | ①

and the PDF doesn't show the right symbol.

Overwrote theme (using http://font.ubuntu.com/) :

```
base:
  font_family: Ubuntu

font:
  catalog:
    Ubuntu:
      normal: Ubuntu-R.ttf
      bold: Ubuntu-B.ttf
      italic: Ubuntu-RI.ttf
      bold_italic: Ubuntu-BI.ttf
  fallbacks: [Ubuntu]
````
but still saw the same warning and PDF still incorrect.

Added the override for code section (why is this needed when base already set?):

    code:
      font_family: $base_font_family

Now the warning is gone, but the PDF is still incorrect (shows empty rectangle for the callout).

Is there a way to force UTF-8 used? Am I to use different fonts to get this work?

Thanks
