### ISSUE TITLE
Umlauts in Header not working on Windows 7

### ISSUE THREAD

**Issue by sainth-** [asciidoctor/asciidoctor-pdf#437]
I'm using german umlauts in my header. On my linux everything is rendered fine. But on a Windows 7 instead of umlauts there appear curious glyphs (`ÄäÜüÖö` -> `├ä├ñ├£├╝├û├╢`).

Using umlauts in the body is no problem.
During rendering no errors are printed on the command line although using the `--trace` option.

The theme.yml-file is encoded with UTF-8 but I tested it also with CP1252. The result were different glyphs.

Anybody knows how to avoid this issue?

Here a little example:

style-theme.yml:
```YAML
font:
  catalog:
    Arial:
      normal: Arial.TTF
      italic: Ariali.TTF
      bold: Arialbd.TTF
      bold_italic: Arialbi.TTF
page:
  background_color: ffffff
  layout: portrait
  margin: [35mm, 30mm, 20mm, 20mm]
  size: A4
base:
  font_color: 000000
  font_family: Arial
  font_size: 10.5
header:
  height: 20mm
  font_size: 8
  font_family: Arial
  recto_content:
    left: ÄäÜüÖö
  verso_content:
    left: ÄäÜüÖö
```

test.adoc:
```AsciiDoc
ifdef::backend-pdf[:notitle:]
:encoding: utf-8
:lang: de

ÄäÜüÖö
```

Generating PDF with following command:
```
asciidoctor-pdf -a pdf-fontsdir=c://windows//fonts -a pdf-stylesdir=. -a pdf-style=style -o test.pdf test.adoc --trace
```
