### ISSUE TITLE
Changing border_width in YAML theme file has no effect on admonition block borders

### ISSUE THREAD

**Issue by royemmerich** [asciidoctor/asciidoctor-pdf#444]
# Version

```
$ asciidoctor-pdf -V
Asciidoctor PDF 1.5.0.alpha.11 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```
# My Wish

I want to add a border (and background colour) to the admonition blocks in my PDF output.
# What I've Tried

The admonition section of my YAML theme file looks like this:

``` yaml
admonition:
  background_color: f5f5f5
  border_color: 7d7d7d
  border_width: $base_border_width
  padding: [0, $horizontal_rhythm, 0, $horizontal_rhythm]
```
- `background_color` has no effect (I added that).
- changing `border_color`changes the colour of the vertical separator line between the icon and the text.
- changing `border_width` doesn't have the desired effect. I've altered this value to `5`but:
  - no external border appears around the admonition block and
  - the width of the vertical separator line between the icon and the text doesn't change either.

The only way I've managed to achieve anything near to what I'm hoping for is by enclosing my admonitions in a sidebar block as such:

``` asciidoc
****
[NOTE]
====
This is a note admonition block enclosed in a sidebar block +
which seems like a bit of a hack to achieve my wish.
====
****
```
# Question

Any tips on how to achieve my wish?
