### ISSUE TITLE
Allow Header/Footer font properties per column

### ISSUE THREAD

**Issue by igagis** [asciidoctor/asciidoctor-pdf#454]
It would be good to be able to specify different fonts/size/style per column position (left/center/right) in header and footer.
Right now it is only possible to change font settings for the whole header or whole footer.

```
header:
  recto_content:
    center: blah blah
    center_font_family: Courier
```

**Comment by mojavelinux** [comment]
That's reasonable. However, I think we may have to rethink the key structure. We should rename recto_content to recto_page.

```
header:
  recto_page:
    center:
      content: blah
      font_family: Courier
```

wdyt?

If you aren't customizing the font, you could write it as:

```
header:
  recto_page:
    center: blah
```

In this case, the position is assumed to be the content.

**Comment by igagis** [comment]
Looks OK.
And recto_content could be deprecated but still functional to provide backwards compatibility.

**Comment by mojavelinux** [comment]
Yes, I was thinking about backward compatibility. But likely we won't keep it for 1.5.0 since this is still alpha (one of the key reasons we are still in alpha). I'll phase it out maybe in beta.

**Comment by mojavelinux** [comment]
Now that I've restructured the keys for the content, I can accommodate the font settings as follows:

```yaml
header:
  recto:
    center:
      content: blah
      font_family: Courier
```

I'm going to start by experimenting with `font_color` as that will be easiest to implement.

Open question: Should we name the segment for face "recto_page" and "verso_page" instead of "recto" and "verso", respectively? (Since I'm remapping the legacy keys, I could still do that without breaking existing themes).
