### ISSUE TITLE
Use different link_font_color in header and footer

### ISSUE THREAD

**Issue by cmiagika** [asciidoctor/asciidoctor-pdf#472]
It would be nice if I can customize the link color of the footer separate.
Maybe it is possible and I'm missing something?

link:
    font_color: green

footer:
    link_font_color: red

**Comment by mojavelinux** [comment]
You are not missing anything. At the moment the link color is universal.

**Comment by mojavelinux** [comment]
This can now be solved using a custom inline role. In your theme file, define a role, then apply that role to the link in the footer:

```
extends: default
role:
  footer-link:
    font-color: #00AA00
footer:
  recto:
    left:
      content: 'https://asciidoctor.org[Asciidoctor,role=footer-link]'
  verso:
    right:
      content: 'https://asciidoctor.org[Asciidoctor,role=footer-link]'
```
