### ISSUE TITLE
Drop lines with unresolved attributes in running content

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#522]
To allow for conditional text in running content, drop lines which contain unresolved attributes after substitutions get applied. Do it in such a way that a warning message is not issued.

Example:

```yaml
footer:
  recto:
    left:
      content: |
        Keep this line
        {unresolved-attribute} nuke this line
        Keep this line
```
