### ISSUE TITLE
Header that resembles latex

### ISSUE THREAD

**Issue by toplac** [asciidoctor/asciidoctor-pdf#589]
Hello, 

first of all I really like writing asciidcotor. I am currently working on my master thesis (PDF) and considering adoc over latex. 
One thing I am currenlty unable to achieve is the following: 

![header](https://cloud.githubusercontent.com/assets/1736327/18951455/9aa038e2-8645-11e6-9705-97c37c91856e.png)

The closest I get is using the following in my theme: 

    header:
       height: 0.75in
       line_height: 1
       recto_content:
          right: '{section-title}'
       verso_content:
          right: '{section-title}'`

But there are two things missing: 
1. I am unable to daw a straight line. 
2. Given the snippet below i am unable to find an attribute matching only Section 1 and Section 2. 
Section Title also matches for the subsections. 

    == Section 1
    === Subsection 1.1
    === Subsection 1.2
    == Section 2
    === Subsection 2.1

Is it currently possible to achieve what I have described?

**Comment by mojavelinux** [comment]
The header and footer support a border, so you can get the line you want using the following:

```yaml
header:
  border_color: #000000
  border_width: 0.5
```

If the doctype is book, you can refer to these top-level sections using the attribute reference `{chapter-title}`. If the doctype is article, then there's no way currently to distinguish between section levels. Suggestions welcome.

Btw, I encourage you to migrate to the new structure for running content:

```yaml
header:
  border_color: #000000
  border_width: 0.5
  height: 0.75in
  line_height: 1.5
  vertical_align: bottom
  recto:
    right:
      content: '{chapter-title}'
  verso:
    right:
      content: $header_recto_right_content
```

**Comment by toplac** [comment]
Thanks for your reply. The border is working fine and more or less what i was looking for (in addition to using :doctype: book 

This is how my theme looks and its working as expected: 

``` yaml 
header:
  border_color: #000000
  border_width: 0.5
  height: 0.75in
  line_height: 1.5
  vertical_algin: bottom
  recto_content:
    right: '{chapter-title}'
  verso_content:
    right: '{chapter-title}'
```

When using the following: 

``` yaml
header:
  border_color: #000000
  border_width: 0.5
  height: 0.75in
  line_height: 1.5
  vertical_algin: bottom
  recto:
    right:
      content: '{chapter-title}'
  verso:
    right:
      content: $header_recto_right_content
```

The border is drawn, but no chapter title is inserted (its blank)

Am I missing something?
