### ISSUE TITLE
Running content cannot access part-title as attribute

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#596]
We use output type book and would like to add the text of our parts to the running footer. Works fine for chapter-title and section-title. But not for part-title.

Example

```
= Part
== Chapter
=== Section
```

Output customizing:

```
footer:
 # additional attributes for content:
 # * {page-count}
 # * {page-number}
 # * {document-title}
 # * {document-subtitle}
 # * {chapter-title}
 # * {section-title}
 # * {section-or-chapter-title}
 recto_content:
   right: '{chapter-title}'
   verso_content:
    left: '{page-number}'
```

I tried part-title instead of chapter-title but this seem not to be supported.
