### ISSUE TITLE
header on a title and toc pages

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#606]
Is there a way in theme customization to have header on a title and toc page?

I have the following in a theme:

```
 header:
   font_size: $base_font_size_small
   height: $base_line_height_length * 6.0
   vertical_align: middle
   recto:
       columns: "<30% 40% >30%"
       left:
         content: 'image:logo/logo-1.png[a, scaledwidth="20%"]'
       right:
         content: 'image:logo/logo-2.png[a, scaledwidth="20%"]'
   verso:
       columns: "<30% 40% >30%"
       left:
         content: 'image:logo/logo-1.png[a, scaledwidth="20%"]'
       right:
         content: 'image:logo/logo-2.png[a, scaledwidth="20%"]'
```
