### ISSUE TITLE
Footer text does not wrap correctly

### ISSUE THREAD

**Issue by bannmann** [asciidoctor/asciidoctor-pdf#608]
asciidoctor-pdf has a problem with long footer/header text, as mentioned in issue #89:

> > If the content becomes too long (like very long {document-title}) make it wrap around so it does not clash with text in other positions
> 
> It will wrap, but as you've pointed out, it does that after clashing with content in a neighboring position. What we need are stop columns. The best thing to do here is probably to switch to using the columnar/table layout so that the PDF engine will automatically handle this behavior.

This is a problem for us because our existing documents have the following disclaimer text in the middle of the footer, but also page numbers in the left and right cells:

> This document is intended for the internal use of recipients only and may not be distributed externally or reproduced for external distribution in any form without express written permission.

With asciidoctor-pdf, the text from the middle cell touches the page numbers. Adding `columns` spec did not help.

As a workaround, I forced a line break at a certain position in the footer text by using a multiline yaml string (with `|`) and a `+` in front of the newline (as mentioned in the theming guide). However, asciidoctor-pdf should really wrap this automatically.

**Comment by mojavelinux** [comment]
This was implemented in alpha.13 to address #449. It is not on by default, so you'll need to explicitly enable it by declaring a columns specification. See https://github.com/asciidoctor/asciidoctor-pdf/issues/449#issuecomment-241635466 for an example.

> This is a problem for us because our existing documents have the following disclaimer text in the middle of the footer, but also page numbers in the left and right cells:

This is precisely the feature that the columns specification addresses. Here's how that might look in your case:

```yaml
footer:
  font-size: 10
  height: 1in
  recto:
    columns: "<25%,=50%,>25%"
    right:
      content: '{page-number}'
    center:
      content: >
        A long string of legal text that will wrap across multiple lines if it's length exceeds the allotted width of this column.
```
