### ISSUE TITLE
Custom theme fallback font error

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#609]
I have custom theme which defines some fonts.

```
font:
  catalog:
    Main:
      normal: roboto-regular.ttf
      bold: roboto-bold.ttf
      italic: roboto-italic.ttf
      bold_italic: roboto-bolditalic.ttf
    Mono:
      normal: roboto-mono-regular.ttf
      bold: roboto-mono-bold.ttf
      italic: roboto-mono-italic.ttf
      bold_italic: roboto-mono-bolditalic.ttf
    Heading:
      normal: cuprum-regular.ttf
      bold: cuprum-bold.ttf
      italic: cuprum-italic.ttf
      bold_italic: cuprum-bolditalic.ttf
 ```
It works but no special symbols are rendered.

Now following the documentation I have added a fallback font:

```
font:
  catalog:
    Main:
      normal: roboto-regular.ttf
      bold: roboto-bold.ttf
      italic: roboto-italic.ttf
      bold_italic: roboto-bolditalic.ttf
    Mono:
      normal: roboto-mono-regular.ttf
      bold: roboto-mono-bold.ttf
      italic: roboto-mono-italic.ttf
      bold_italic: roboto-mono-bolditalic.ttf
    Heading:
      normal: cuprum-regular.ttf
      bold: cuprum-bold.ttf
      italic: cuprum-italic.ttf
      bold_italic: cuprum-bolditalic.ttf
    DroidSansFallback:
      normal: droid-sans-fallback.ttf
      bold: droid-sans-fallback.ttf
      italic: droid-sans-fallback.ttf
      bold_italic: droid-sans-fallback.ttf
  fallbacks:
    - DroidSansFallback
```

And asciidoctor-pdf complains:

```
undefined method `unpack' for nil:NilClass
   Use --trace for backtrace
```

And the document I try to render has only

```
From -> to => smth
```
Am I missing smth?
