### ISSUE TITLE
Nested unordered lists crash the renderer when a non-default font is in use

### ISSUE THREAD

**Issue by tkfu** [asciidoctor/asciidoctor-pdf#619]
If I create an asciidoc file that has an unordered list in it with nested items, it yields the following error when trying to render it using my custom stylesheet:

```
$ asciidoctor-pdf -a pdf-style=my-theme.yml -a pdf-fontsdir=fonts simple.adoc 
Prawn::Errors::CannotFit
  Use --trace for backtrace
```

This appears to happen when the font is missing the bullet glyphs that asciidoctor uses for specific nested levels.

The simplest examples of failing files I can produce are as follows:

Modify default-theme.yml to add Roboto: 

(note: I chose Roboto arbitrarily; the one I'm actually trying to use isn't freely licensed. I've reproduced this with a number of different fonts, however. The difference is in how many of the glyphs the font has. Helvetica Neue, for example, works up until the 2nd nesting level, but fails beyond that.)

**my-theme.yml**

```
font:
  catalog:
    Roboto:
      normal: Roboto-Light.ttf
      bold: Roboto-Bold.ttf
      italic: Roboto-LightItalic.ttf
      bold_italic: Roboto-BoldItalic.ttf
[...]
base:
[...]
  font_family: Roboto
```

**simple.adoc**

```
= Test Document

test

== Heading 1

* item
** item
*** item
```

If I remove the fallback font from the stylesheet, the document will render, but without bullets for the 2nd and 3rd levels of nesting.

**Comment by habamax** [comment]
you have to use fallback font to avoid that problem

I for myself copied M+ fallback font which default theme uses, added to the theme and this error had gone away.

**Comment by habamax** [comment]
My theme setup regarding fonts:
```
font:
  catalog:
    Main:
      normal: roboto-regular.ttf
      bold: roboto-bold.ttf
      italic: roboto-italic.ttf
      bold_italic: roboto-bolditalic.ttf
    Mono:
      normal: roboto-mono-regular.ttf
      bold: roboto-mono-bold.ttf
      italic: roboto-mono-italic.ttf
      bold_italic: roboto-mono-bolditalic.ttf
    Heading:
      normal: cuprum-regular.ttf
      bold: cuprum-bold.ttf
      italic: cuprum-italic.ttf
      bold_italic: cuprum-bolditalic.ttf
    Fallback:
      normal: mplus1p-regular-fallback.ttf
      bold: mplus1p-regular-fallback.ttf
      italic: mplus1p-regular-fallback.ttf
      bold_italic: mplus1p-regular-fallback.ttf
  fallbacks:
    - Fallback
```
