### ISSUE TITLE
custom theme callouts are not rendered

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#622]
I have created custom theme with the fonts taken from gem file:

```
font:
  catalog:
    Main:
      normal: notoserif-regular.ttf
      bold: notoserif-bold.ttf
      italic: notoserif-italic.ttf
      bold_italic: notoserif-bolditalic.ttf
    Mono:
      normal: mplus1mn-regular-ascii-conums.ttf
      bold: mplus1mn-bold-ascii.ttf
      italic: mplus1mn-italic-ascii.ttf
      bold_italic: mplus1mn-bolditalic-ascii.ttf
    Heading:
      normal: cuprum-regular.ttf
      bold: cuprum-bold.ttf
      italic: cuprum-italic.ttf
      bold_italic: cuprum-bolditalic.ttf
    Fallback:
      normal: mplus1p-regular-fallback.ttf
      bold: mplus1p-regular-fallback.ttf
      italic: mplus1p-regular-fallback.ttf
      bold_italic: mplus1p-regular-fallback.ttf
  fallbacks:
    - Fallback

```

for `base` I use Main font (which is a ttf files copied from distribution)

With that theme fonts I get the following result:
```
= Проекты
:author: blabla
:experimental:
:toc: left
:toclevels: 3
:icons: font
:sectnums:
:source-highlighter: coderay
:pdf-style: default
:revdate: 2016-10-11

== section
.Файл `context.xml`
[source,xml]
----
...
<Resource name="jdbc/dqd" auth="Container" type="javax.sql.DataSource"
        testOnBorrow = "true"
        validationQuery = "SELECT 1 FROM SYSIBM.SYSDUMMY1"
        validationInterval="1800000"
        maxActive="100" maxIdle="30" maxWait="-1"
        username="xxx" password="xxx" driverClassName="org.apache.derby.jdbc.ClientDriver" <1>
        url="jdbc:derby://localhost:1527/mart"/> <2>
        привет тебе!!!
...
----

<1> username и password ...
<2> подставили `mart`
```

![asciidoctor-pdf-callouts](https://cloud.githubusercontent.com/assets/234774/19300650/168a1220-9064-11e6-9cba-b99ae784150b.png)

If theme is omitted callouts in the text are rendered OK.

What else should I set up?
