### ISSUE TITLE
Default theme font refinements

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#633]
What do you think about making font names to be more generic?

Like `Body Font` instead of `Noto Serif` and `Fixed Width` instead of `M+ 1mn`?

The issue it solves (minor one) is, if you only want to change fonts, you do it once in a font catalog.

At the moment, following the documentation where you change font names to Roboto, you also have to apply that name to a various blocks (`base` for a Roboto instead of Noto Serif, `conum` and `literal` for a fixed width font you have instead of M+ 1mn)

You can actually do it right now leaving font catalog names as it is, changing only font names. But Noto Serif as Arial looks a bit dirty.

```
font:
  catalog:
    Noto Serif:
      normal: arial-regular-subset.ttf
      bold: arial-bold-subset.ttf
      italic: arial-italic-subset.ttf
      bold_italic: arial-bold_italic-subset.ttf
```

**Comment by mojavelinux** [comment]
It's now possible to define brand variables at the top of the theme file. This would allow you to accomplish what you are shooting for without introducing any additional complexity in the converter.

```
brand:
  body_font: Noto Serif
base:
  font_family: $brand_body_font
```

**Comment by habamax** [comment]
Well, the issue was with the way default theme is set up. It uses real font names instead of generic (Noto Serif vs Body Font).
In my themes I have changed them to 

```
font:
  catalog:
    Main:
      normal: Merriweather-Light.ttf
      bold: Merriweather-Bold.ttf
      italic: Merriweather-LightItalic.ttf
      bold_italic: Merriweather-BoldItalic.ttf
    Mono:
      normal: FantasqueSansMono-Regular.ttf
      bold: FantasqueSansMono-Bold.ttf
      italic: FantasqueSansMono-Italic.ttf
      bold_italic: FantasqueSansMono-BoldItalic.ttf
    Heading:
      normal: Oswald-Regular.ttf
      bold: Oswald-SemiBold.ttf
      italic: Oswald-Regular.ttf
      bold_italic: Oswald-SemiBold.ttf
...
```

The thing is that many of us (?) try to reuse default theme and thus it would be much easier to change font names in a catalog only.
