### ISSUE TITLE
Header and Footer customization seem to be ignored

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctor-pdf#657]
1. Copy the default theme as custom-theme.yml.
2. Change something like A4 to letter or portrait to landscape

Observe that the changes are effective.

3. Restore any changes from 2
4. Change something about the footer, say...

```yaml
footer:

  # no changes until...

  recto:
    right:
      content: 'Yo, look at me:  {page-number}'
```
No effect, all pages still just have the page number.

I'm using a gradle build that looks like the gradle example with theme.

```
// ...
  dependencies {
    classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
    classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11'
  }
// ...
asciidoctor {
  backends 'pdf'
  sourceDir "src/asciidoc"
  attributes 'pdf-stylesdir':'theme', 'pdf-style':'custom'
}

```

**Comment by DavidGamba** [comment]
Maybe that space between footer and recto?

**Comment by kastork** [comment]
Arg, you had me going there....  But no, there's no space in the actual file, just the comments that come with the copy/pasted default theme file.

```yaml
footer:
  font_size: $base_font_size_small
  # NOTE if background_color is set, background and border will span width of page
  border_color: dddddd
  border_width: 0.25
  height: $base_line_height_length * 2.5
  line_height: 1
  padding: [$base_line_height_length / 2, 1, 0, 1]
  vertical_align: top
  #image_vertical_align: <alignment> or <number>
  # additional attributes for content:
  # * {page-count}
  # * {page-number}
  # * {document-title}
  # * {document-subtitle}
  # * {chapter-title}
  # * {section-title}
  # * {section-or-chapter-title}
  recto:
    right:
      content:  'Yo, look at me: {page-number}'
      #content: '{section-or-chapter-title} | {page-number}'
      #content: '{document-title} | {page-number}'
  verso:
    left:
      content: 'Yo, look at me: {page-number}'
      #content: '{section-or-chapter-title} | {page-number}'
      #content: '{document-title} | {page-number}'
```

**Comment by DavidGamba** [comment]
did you give it a try with the ruby gem over the command line? (make sure to use the pre-release one).

This is what I have in the makefile of a project not big enough to make it worth using the API.

````Makefile
ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

BUILD_PDF= asciidoctor-pdf \
                -a numbered \
                -a data-uri \
                -a toc=right \
                -a toclevels=2 \
                -a allow-uri-read \
                -a 'company=my company' \
                -a basedir=$(ROOT_DIR) \
                -a pdf-fontsdir=$(ROOT_DIR)/fonts \
                -a pdf-stylesdir=$(ROOT_DIR) \
                -a pdf-style=stylesheets/theme.yml \
                -r asciidoctor-diagram

target-pdf:
        $(BUILD_PDF) target-file.adoc

````

And my footer:

````yml
footer:
   font_size: 7
   height: 0.5in
   border_color: #000000
   recto: # odd pages
      left:
         content: '{page-number}'
      center:
         content: '©2016 {company}, {docdate}'
      right:
         content:  image::images/logo.png[width=150]
   verso: # even pages
      left:
         content:  image::images/logo.png[width=150]
      center:
         content: '©2016 {company}, {docdate}'
      right:
         content: '{page-number}'
````
