### ISSUE TITLE
Problem with my font

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#667]
Hi,

I have a problem with my font configured in YAML (I must use the font Cuprum).

```
base:
  ...
  font_family: Cuprum
  ...

conum:
  font_family: M+ 1mn
  font_color: $literal_font_color
  font_size: $base_font_size
  line_height: 4 / 3
```

But when my adoc contains conum, I have this error
```
F:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/prawn-2.1.0/lib/prawn/text/formatted/line_wrap.rb:209:in `update_output_based_on_last_fragment': Prawn::Errors::CannotFit (Prawn::Errors::CannotFit)
```

idem with second level of list (**)
```
* apples
* oranges
** temple
** navel
* bananas
```

Help me please ;-)
Jérôme
