### ISSUE TITLE
Styling of part pages

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#671]
At the moment the styling of a part page is quite rudimentary. It is only possible to style the h1 element as with:

```
heading:
  h1:
    font_size: $base_font_size * 1.8
    font_color: 999999
    font_style: italic
    align: right
```

We would need to style part pages similar like title pages.

```
title_page:
  align: right
  logo:
    top: 40%
    align: right
    image: image:GrayMagier.png[pdfwidth=17%]
  title:
    top: 55%
    font_size: $heading_h1_font_size * 1.4
    font_color: 999999
    line_height: 0.9
```

**Comment by vogella** [comment]
@fap- can you have a look?

**Comment by mojavelinux** [comment]
This seems pretty reasonable. In the meantime, you can override the `layout_part_title node, title, opts` method similar to what Matt Raible did for the InfoQ minibook.

https://github.com/mraible/infoq-mini-book/blob/master/src/main/ruby/asciidoctor-pdf-extensions.rb

**Comment by mojavelinux** [comment]
If we do this, we should probably abstract away a generic method that handles a configuration-driven, full-page layout.

**Comment by fap-** [comment]
I'd like to start working on this. Do you have some suggestions how this generic method should work?
Do you mean a generic abstraction above all the layout_<page> methods and/or would you like to extend customizability above the level that the title page currently allows?

**Comment by fap-** [comment]
@mojavelinux I thought about this for a while and I'd really like to make the layout more extendable.
The way the theme gets loaded into an OpenStruct instead of an Hash makes it harder to utilize the structured nature of Yaml to make this possible. Is there a reason for the decision to load it this way?

I'd propose a structure likes this. The new flexible parts are highlighted with a # comment.

```
pages:
  title:
    align: right
    images:                                                 # insert arbitrary images without asciidoctor knowing about them beforehand
      logo:
        top: 40%
        align: right
        image: image:GrayMagier.png[pdfwidth=17%]
    title:
      top: 55%
      font_size: $heading_h1_font_size * 1.4
      font_color: 999999
      line_height: 0.9
    subtitle:
      font_size: $heading_h3_font_size
      font_style: bold_italic
      line_height: 1
    authors:
      margin_top: $base_font_size * 1.25
      font_size: $base_font_size_large
      font_color: 181818
  chapter:
    # default case, special chapters inherit these
    title:
      top: 55%
      font_size: $heading_h1_font_size * 1.4
      font_color: 999999
      line_height: 0.9
    images:
      logo:
        top: 40%
        align: right
        image: image:GrayMagier.png[pdfwidth=17%]
    chapters:
      colophon:                                               # special layout for certain chapter pages, gets matched with section_title.downcase
        align: left
        title:
          top: 50%
        images:                                               # insert arbitrary images without asciidoctor knowing about them beforehand
          flower:
            top: 60%
            align: right
            image: image:FlowerPower.png
        texts:                                                # makes it possible to insert arbitrary text to specific positions on chapter page
          underline:
            top: 50%
            text: "/////////"                                 # I'd rather have a way to give an id to a line of text in the asciidoc and reference it here than to have this in the theme
            margin_top: $base_font_size * 1.25
```
There should probably be a `:chapter_page_on_own_page:` option to trigger `start_new_page` after the layout is done. (with a better name, of course :laughing: )

I'm not sure if this is going in the right direction but I'd like to hear your thoughts on the idea.

**Comment by fap-** [comment]
The implementation we are currently using is found here: https://github.com/vogellacompany/asciidoctor-pdf/tree/styling_of_part_pages
This implementation is less generic and less powerful than what I proposed in my post above, but it works around the (perceived) limitations of the theme loading.
Also note that possible `page_prefix`s are hard coded, this could be solved with a list in the adoc file that contains possible `page_prefix` values.
eg. `:chapter_pages: index, appendix`

Example config:
```
chapter_page:
  align: right
  logo:
    top: 10%
    align: right
    image: image:GrayMagier.png[pdfwidth=17%]
  title:
    top: 70%
    font_size: $heading_h1_font_size * 1.4
    font_color: 999999
    line_height: 0.9
appendix_page:
  align: left
  logo:
    top: 30%
    align: right
    image: image:GrayMagier.png[pdfwidth=17%]
  title:
    top: 50%
    font_size: $heading_h1_font_size * 1.4
    font_color: 999999
    line_height: 0.9
```
