### ISSUE TITLE
Support formatting of Table of Contents title

### ISSUE THREAD

**Issue by mdreier** [asciidoctor/asciidoctor-pdf#701]
I would like a feature to further customize the formatting of the title of the Table of Contents. Currently, it is inheriting the format of a level 2 heading. This is, however, not working for my requirements.

My suggestion would be to allow overwriting the inherited settings in the toc_title section, such as:
```
toc:
  title:
    font_size: 16
    text_transform: uppercase
```
