### ISSUE TITLE
Make page break before sections configurable

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#74]
Make the page break behavior before sections configurable via the theme. The theme should be able to dictate which headings trigger an automatic page break.

**Comment by mojavelinux** [comment]
Currently, page breaks occur before level-1 sections (chapters) when the doctype is book. However, they do not occur for level-0 sections (parts).

When the doctype is article, page breaks do not occur at all.

We'll need to think about how to express this.

**Comment by cascer1** [comment]
I would love to be able to specify in my theme where breaks should and shouldn't go. Something like:

```
page:
  heading-1:
    break:
      before: true
      after: false
```

**Comment by mojavelinux** [comment]
I'm aiming to make the theme as faithful to and familiar as CSS as possible. Therefore, I'd like to draw on the properties defined in the CSS page spec.

See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Pages

So it might be something like:

```
heading:
  h1:
    page_break_after: always
    page_break_before: auto
```

One problem we have is with identifying terminology. Right now we use "heading" and "h1", but not "chapter". In AsciiDoc, an h2 isn't always a chapter and an h1 isn't always a part. So we'll probably need to add those keywords to compliment h1, h2, etc, which are the general "bridge heading" case.
