### ISSUE TITLE
non win-1252 characters in SVG

### ISSUE THREAD

**Issue by nbkolchin** [asciidoctor/asciidoctor-pdf#777]
Asciidoctor input:

```
[blockdiag, format="svg"]
.Пример диаграммы
----
blockdiag {
  A[label="изображение"];
  B[label="color filtering"];
  A -> B;
}
----
```

Theme file:

```
font:
  catalog:
    PTAstraSerif:
      normal: PTAstraSerif-Regular.ttf
      bold: PTAstraSerif-Bold.ttf
      italic: PTAstraSerif-Italic.ttf
      bold_italic: PTAstraSerif-BoldItalic.ttf
  fallbacks:
    - PTAstraSerif
base:
  font_family: PTAstraSerif
```

Generated svg:
```
...
  <text fill="rgb(0,0,0)" font-family="sans-serif" font-size="11" font-style="normal" font-weight="normal" text-anchor="middle" textLength="64" x="320" y="67">color filtering</text>
...
```

Asciidoctor execution:
```
$ asciidoctor-pdf \
    -a pdf-style=$HOME/.asciidoctor/themes/basic-theme.yml \
    -a pdf-fontsdir=$HOME/.asciidoctor/fonts \
    -r asciidoctor-diagram \
    test.adoc
The following text could not be fully converted to the Windows-1252 character set:
| изображение
```

There is no way to specify SVG font for 'blockdiag', it will always use "sans-serif".

Afaik, there is no way to replace default "sans-serif" in asciidoctor.

If I manually edit generated svg and change "sans-serif" with "PTAstraSerif", everything work without errors.

**Comment by mojavelinux** [comment]
I'd argue this bug lies with [Prawn SVG](https://github.com/mogest/prawn-svg). Asciidoctor does allow you to map generic font names like sans-serif in your font catalog.

```
font:
  catalog:
    sans-serif:
      normal: PTAstraSerif-Regular.ttf
      bold: PTAstraSerif-Bold.ttf
      italic: PTAstraSerif-Italic.ttf
      bold_italic: PTAstraSerif-BoldItalic.ttf
```

However, Prawn SVG is not respecting these mappings. If it sees a generic font name (e.g., sans-serif), it maps it to a built-in AFM font (e.g., Helvetica) without first consulting the font registry. You can see where this happens here:

https://github.com/mogest/prawn-svg/blob/5d40c5fab3eabc34650269c663931f98c3b4430e/lib/prawn/svg/font.rb#L24

If Prawn SVG where to consult the font registry first, everything would work.

There is a workaround for this problem. Create a file named *prawn-svg-patch.rb* with the following content:

```
require 'prawn-svg'

Prawn::SVG::Font::GENERIC_CSS_FONT_MAPPING['sans-serif'] = 'PTAstraSerif'
```

Then load it when you are calling Asciidoctor PDF:

```
$ asciidoctor-pdf -r ./prawn-svg-patch.rb -r asciidoctor-diagram diagram.adoc
```

Would you be willing to file the bug/feature request in Prawn SVG?
