### ISSUE TITLE
Can't properly render URLs due to unknown glyphs

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#795]
I'm linking to asciidoctor.org in my document. I'm using the TitilliumWeb font from Google for my template.

When I output the document I get error messages about non 1252 characters (see #794) but it also complains about the URLs. None of the other URLs in the document are affected by this.

The URLs are defined in the document like this:

```
==== Syntax

Die Grundlage für der Dokumente ist das AsciiDoc Format (link:http://asciidoctor.org/docs/what-is-asciidoc/[]). Es handelt sich um eine simple Syntaxsprache die es erlaubt mit einfachen Formatierungszeichen komplex strukturierte Dokumente zu erzeugen. Gleichzeitig ist das Format aber mächtig genug um nahezu alle Anforderungen an die Inhalte der Softwaredokumentation zu erfüllen. Das Format und die damit verbundenen Werkzeuge werden von einer aktiven Entwicklercommunity ständig weiter entwickelt.

Dabei bleibt alles in lesbarer Schreibweise in den Quelldokumenten erhalten so dass jeder Benutzer in kürzester Zeit alle Aspekte des Dokumentes verstehen und bearbeiten kann.

[TIP]
====
Das Format bietet eine riesige Bandbreite an Formatierungsoptionen und Möglichkeiten um die erzeugten Dokumente an seine Bedürfnisse anzupassen. Diese alle auch nur ansatzweise zu erklären würde den Rahmen dieses Dokumentes sprengen. Machen Sie sich einfach selbst ein Bild: http://asciidoctor.org/docs/user-manual/
```

Interestingly when I rewrite the URLs to look like this:

`link:http://asciidoctor.org/docs/what-is-asciidoc/[What Is AsciiDoc]`
and
`link:http://asciidoctor.org/docs/user-manual/[AsciiDoctor User Manual]`

It works fine and does not complain.

Why is it that only these URLs are interpreted incorrectly? I use several other URLs in the document and none of them gets rendered with the "not"-glyph.

![screenshot from 2017-03-31 19-42-12](https://cloud.githubusercontent.com/assets/4920542/24562347/ce732e50-164a-11e7-8343-085d1879fb79.png)
![screenshot from 2017-03-31 19-42-20](https://cloud.githubusercontent.com/assets/4920542/24562346/ce721b14-164a-11e7-88a7-dc47794e738c.png)

**Comment by mojavelinux** [comment]
> When I output the document I get error messages about non 1252 characters 

This is a clear indication you're using a built-in AFM font instead of a TTF font for your main text. You should almost never use the built-in AFM fonts.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#built-in-afm-fonts

The reason for the "not" glyph here is because we are inserting a "break" hint in raw URLs to allow them to be wrapped. The character we use is a zero-width space, which is not available when using an AFM font.

We could introduce an attribute to disable this behavior (or detect the use of the AFM font), but to be honest, you should not be using an AFM font with Asciidoctor PDF.

**Comment by mojavelinux** [comment]
Btw, this is not specific to Asciidoctor URLs. It has to do with whether the URL contains a break opportunity, which is essentially a forward slash.

**Comment by mojavelinux** [comment]
>  I'm using the TitilliumWeb font from Google for my template.

I'm not convinced you've configured it correctly. Do you have the following declaration?

```
base:
  font_family: TitilliumWeb
```

?

**Comment by mojavelinux** [comment]
It seems reasonable to me to detect whether the font supports zero-width space (in our case, as long as it's not an AFM font). The glyph does not need to be present in the non-AFM font as Prawn does not attempt to render the zero-width space glyph in that case.

There are some future edge cases where the font used to render the link could be different than the current font at the time the breakable logic is performed, so we may have to relocate the logic...but this is going to cover 99% of themes.

**Comment by mojavelinux** [comment]
It's interesting why this is a problem. Prawn encodes the string before it starts to render it. When the font is AFM, Prawn encodes to windows-1252. The zero-width space is not in the windows-1252 charset, so therefore it gets replaced with the not symbol. Prawn only looks for break opportunities at a zero-width space. But there's no way to have a windows-1252 encoded string w/ a zero-width space. So basically it is Prawn that prevents us from using the break hint feature when an AFM font is in use.

In the end, I'd argue that Prawn doesn't really work properly with AFM fonts (as some of its features get implicitly disabled).

**Comment by mojavelinux** [comment]
> There are some future edge cases where the font used to render the link could be different than the current font at the time the breakable logic is performed

I'm confident I have this covered now.

**Comment by mojavelinux** [comment]
The one exception is tables. I can't detect which font is used for tables from where we add break hints to URIs. This is just one of those places where the cart gets in front of the horse in Prawn.

**Comment by mojavelinux** [comment]
Okay, I found a better way to do this that covers all cases of using an AFM font. It even allows all built-in glyphs to work out of the box, such as markers on unordered lists and narrow spaces inside button brackets and around dashes. Basically, we're now making suitable substitution when converting to an AFM font. (I suppose we still could replace conums, but let's handle that in a separate issue).

**Comment by r0ckarong** [comment]
I have this configured for the use of the font. I am already a little confused as to how to define a document wide font in this way.

Font Catalog
```
font:
  catalog:
    # TitilliumWeb
    TitilliumWeb:
      normal: titilliumweb-normal.ttf
      bold: titilliumweb-bold.ttf
      italic: titilliumweb-italic.ttf
      bold-italic: titilliumweb-bold_italic.ttf
... More Fonts (Standard)
´´`
Brand style
´´´
brand:
  # font: Noto Serif
  font_family: TitilliumWeb
  aragoblue: #004481
  darkblue: #031c31
  lightgrey: #898989
  blue_gradient:
    start: #25b5ec
    end: #20ecff
  purple_gradient:
    start: #9524a6
    end: #ca98df
  orange_gradient:
    start: #ff7a20
    end: #ff9920
  red: #ee2957
  yellow: #e2ee29
  green: #47d05b
  darkred: #ba3925
```
base definition
```
base:
  align: justify
  # color as hex string (leading # is optional)
  font_color: 333333
  font_family: $brand_font
  font_size: 10
  line_height_length: 13.8
  line_height: $base_line_height_length / $base_font_size
  font_size_large: round($base_font_size * 1.25)
  font_size_small: round($base_font_size * 0.85)
  font_size_min: $base_font_size * 0.75
  font_style: normal
  border_color: #EEEEEE
  border_radius: 4
  border_width: 0.5
```

What I'm confused by is if I declare "font: TitilliumWeb" in the brand section the document will not pick up the change and falls back. If I do it with font_family it works.
