### ISSUE TITLE
Warn if variable reference in theme can't be resolved

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#801]
When processing the theme file, issue a warning if a theme variable cannot be resolved. Currently, the value resolves to empty string, which can lead to some really hard to trace problems.

Example:

```
brand:
  color_1: aa0000
base:
  font_color: $brand_foobar
```

This should issue the following warning:

```
asciidoctor: WARNING: unresolved variable reference in PDF theme: $brand_foobar
```
