### ISSUE TITLE
Footer Configuration Documentation Mismatch

### ISSUE THREAD

**Issue by mark-schaefer** [asciidoctor/asciidoctor-pdf#829]
Following the documentation in the theming guide a key for footer configuration would be e.g. 
`footer_recto_left_content`. However, I have to user `footer_recto_content_left`

I am using the Asciidoctor Maven Plugin in Version 1.5.5

**Comment by mojavelinux** [comment]
It's very likely you are using an older alpha of Asciidoctor PDF. Can you confirm which version you are using?

If you need to continue using an older version, then please select the corresponding branch to read the theming guide. For example: https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.0.alpha.12/docs/theming-guide.adoc#running-content

If you are using the alpha.15, then the proper structure is. `footer_<side>_<position>_content`. For example:

```
footer:
  height: 0.75in
  line_height: 1
  recto:
    right:
      content: '{section-or-chapter-title} | *{page-number}*'
  verso:
    left:
      content: '*{page-number}* | {chapter-title}'
```
