### ISSUE TITLE
Setting background image in new theme file?

### ISSUE THREAD

**Issue by akrabat** [asciidoctor/asciidoctor-pdf#860]
Hi,
I'm writing a new theme file and want to use `page_background_image` where the image is in a directory called `images` which is subdirectory of the directory where my `theme.yml` file is. Is this possible?

theme.yml:
```yml
page:
  layout: portrait
  margin: [0mm, 0mm, 0mm, 0mm]
  size: A4
  background-image: image:test.png[]
```

Creation of pdf:
```bash
$ asciidoctor-pdf  -a pdf-style='./theme.yml' -a imagesdir='./images' test.adoc
```

This doesn't work though as I get this:

```
asciidoctor: WARNING: page background image not found or readable: /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/data/themes/test.png
```

Is there a way to tell the theme file that my `test.png` is relative to `theme.yml` ?
