### ISSUE TITLE
imagesdir attribute ignored when rendering title page

### ISSUE THREAD

**Issue by jefftp** [asciidoctor/asciidoctor-pdf#878]
When rendering a PDF with asciidoctor-pdf I've run into an issue where I have to specify the full path to an image on the title page only. I can reuse the same image on all the subsequent pages with the normal image macro.

For example:

asciidoctor-pdf -a imagesdir=/usr/local/share/asciidoctor/images -a pdfstyle=theme.yml

Excerpt from theme.yml:

```yaml
title_page:
  #background_image: image:background.png[]
  background_image: image:/usr/local/share/asciidoctor/images/background.png[]
  logo:
    #image: image:logo.png[width=240]
    image: image:/usr/local/share/asciidoctor/images/logo.png[width=240]
[...]
header:
  recto:
    left:
      content: image:logo.png[width=120]
    right:
      content: 'www.example.com'
```

I've commented out the "proper" form for images above because asciidoctor-pdf cannot find the images without specifying the full path.

I've also tried explicitly declaring the imagesdir in the adoc file, this doesn't work either. It appears the title page is rendered before imagesdir is evaluated?
