### ISSUE TITLE
table font_size is not applied for `a|` cells

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#926]
Theme file snippet:

```
base:
  font_size: 12

table:
  border_color: a0a0a0
  border_width: $base_border_width
  font_size: 8.5

```

Asciidoctor snippet:

```
...
| `ORIGIN`
| `VARCHAR(100)`
| Source system code. `ice#dp_contact_official#denied_entity`

| `SOURCE_ID`
| `VARCHAR(200)`
| Identifier of the denied entity in the list of given type.

| `TYPE`
| `INT`
a|
Type of the entity:

- `1` -- Individual Person
- `2` -- Legal entity
- `3` -- Other
...
```

How it looks like:

![image](https://user-images.githubusercontent.com/234774/43508280-2b5fa8ca-9578-11e8-812c-c3c8c0a37a5f.png)

I believe that font size specified for table should be applied to all cells.
