### ISSUE TITLE
Unordered list theming guide issue

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#997]
There is `ulist` in theming guide:

![image](https://user-images.githubusercontent.com/234774/51318068-4cde3f80-1a6a-11e9-944f-1261482ce2a0.png)

I believe it should be `ulist:` and color should be without hash sign, but that is not the real issue. Whatever I try to set up for ulist -- it doesn't have any effect:

For example with the following:

```
ulist:
  marker:
    square:
      content: "\uf140"
      font_color: ff0000
```
I expect to have red bullet. But nothing happens.

**Comment by habamax** [comment]
Okay, to change the color I have to use outline_list:

```
# ordered and unordered list item vertical spacing!
outline_list:
  item_spacing: 2
  marker_font_color: ff0000
```

so it is the documentation issue -- either "future" improvements leaked there or previous info wasn't cleared up.
